In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [25]:
import datetime as dt

In [8]:
df=pd.read_csv('train_file.csv',parse_dates=['APPLICATION CREATED DATE', 'APPLICATION REQUIREMENTS COMPLETE',
       'PAYMENT DATE','LICENSE TERM START DATE',
       'LICENSE TERM EXPIRATION DATE', 'LICENSE APPROVED FOR ISSUANCE',
       'DATE ISSUED', 'LICENSE STATUS CHANGE DATE'])
df

/Users/prakritsinha/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS
0,35342-20020816,1256593,32811,1,CARMEN CAHUE,CLAUDIA'S BRIDAL SHOP,2625 S CENTRAL PARK AVE 1,CHICAGO,IL,60623.0,22.0,28.0,22-28,10.0,1010,Limited Business License,35342.0,RENEW,NaT,2002-06-28,2002-08-21,N,2002-08-16,2003-08-15,2002-08-21,2006-04-11,NaT,25.0,41.843613,-87.714618,"{'latitude': '41.843612879431845', 'longitude'...",AAI
1,1358463-20051116,1639294,262311,29,"ISLA TROPICAL, INC.",ISLA TROPICAL,2825 W MONTROSE AVE,CHICAGO,IL,60618,33.0,23.0,33-23,17.0,1315,Mobile Food Dispenser,1358463.0,RENEW,NaT,2005-09-22,2005-11-03,N,2005-11-16,2006-11-15,2006-04-05,2006-06-12,2006-06-15,60.0,41.961132,-87.699626,"{'latitude': '41.96113244107215', 'longitude':...",AAC
2,1980233-20090722,1980233,345008,1,DJS REMODELING,"DJS REMODELING, INC.",1605 CLAVEY RD 1,HIGHLAND,IL,60035,NaN,NaN,NaN,NaN,1011,Home Repair,1980233.0,ISSUE,2009-06-29,2009-07-22,2009-07-22,N,2009-07-22,2011-07-15,2009-07-22,2009-07-22,NaT,NaN,NaN,NaN,NaN,AAI
3,1476582-20040211,1476582,273121,1,ALL-BRY CONSTRUCTION CO.,ALL-BRY CONSTRUCTION CO.,8 NORTH TRAIL,LEMONT,IL,60439,NaN,NaN,NaN,NaN,1010,Limited Business License,1476582.0,ISSUE,2004-02-10,2004-02-10,2004-02-10,N,2004-02-11,2005-02-15,2004-02-10,2004-02-11,NaT,NaN,NaN,NaN,NaN,AAI
4,1141408-20080516,1896750,213785,1,MCDONOUGH MECHANICAL SERVICE,MCDONOUGH MECHANICAL SERVICE,4081 JOSEPH DR,WAUKEGAN,IL,60087,NaN,NaN,NaN,NaN,1010,Limited Business License,1141408.0,RENEW,NaT,2008-03-24,2008-06-04,N,2008-05-16,2010-05-15,2008-06-04,2008-06-05,NaT,NaN,NaN,NaN,NaN,AAI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85890,12652-20120516,2143400,8011,1,UNITED PARCEL SERVICE,UNITED PARCEL SERVICE,1400 S JEFFERSON ST,CHICAGO,IL,60607.0,11.0,28.0,11-28,1.0,1008,Hazardous Materials,12652.0,RENEW,NaT,2012-03-15,2012-05-07,N,2012-05-16,2014-05-15,2012-05-07,2012-05-08,2012-12-29,NaN,41.863501,-87.642210,"{'latitude': '41.86350135244771', 'longitude':...",AAC
85891,1821421-20070522,1821421,317725,1,"EXPRESS BOARD UP SERVICE, INC.","EXPRESS BOARD UP SERVICE, INC.",8707 VANGUARD DR,MACHESNEY PARK,IL,61115.0,NaN,NaN,NaN,NaN,1800,Board-Up Work,1821421.0,ISSUE,2007-05-21,2007-05-22,2007-05-22,N,2007-05-22,2009-06-15,2007-05-22,2007-05-22,NaT,NaN,NaN,NaN,NaN,AAI
85892,74137-20090116,1939358,8458,2,ARAMARK SMMS LLC,ARAMARK FACILITY SERVICES,2300 WARRENVILLE RD 1ST,DOWNERS GROVE,IL,60515.0,NaN,NaN,NaN,NaN,1010,Limited Business License,74137.0,RENEW,NaT,2008-11-14,2009-01-09,N,2009-01-16,2011-01-15,2009-01-09,2009-12-08,NaT,NaN,NaN,NaN,NaN,AAI
85893,2049545-20111016,2110060,2156,43,GENERAL NUTRITION CORPORATION,GENERAL NUTRITION CENTER # 61,5151 S PULASKI RD SLAB ON GRADE T-21,CHICAGO,IL,60632.0,23.0,NaN,23-,NaN,1010,Limited Business License,2049545.0,RENEW,NaT,2011-08-15,2011-10-03,N,2011-10-16,2013-10-15,2011-10-03,2011-10-11,2012-05-08,NaN,41.799012,-87.723181,"{'latitude': '41.79901235310339', 'longitude':...",AAC
85894,1070196-20040216,1461628,205936,1,JUAN CARLOS ERAZO,CASA DE JUAN RESTAURANT,5814 W FULLERTON AVE,CHICAGO,IL,60639.0,30.0,52.0,30-52,25.0,1006,Retail Food Establishment,1070196.0,RENEW,NaT,2003-12-15,2004-02-06,N,2004-02-16,2005-02-15,2003-12-22,2004-02-09,2005-01-07,NaN,41.924004,-87.771507,"{'latitude': '41.92400390449922', 'longitude':...",AAC

In [7]:
pd. set_option("display.max_columns", None)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85895 entries, 0 to 85894
Data columns (total 32 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ID                                 85895 non-null  object
 1   LICENSE ID                         85895 non-null  int64
 2   ACCOUNT NUMBER                     85895 non-null  int64
 3   SITE NUMBER                        85895 non-null  int64
 4   LEGAL NAME                         85895 non-null  object
 5   DOING BUSINESS AS NAME             85894 non-null  object
 6   ADDRESS                            85895 non-null  object
 7   CITY                               85895 non-null  object
 8   STATE                              85895 non-null  object
 9   ZIP CODE                           85864 non-null  object
 10  WARD                               36194 non-null  float64
 11  PRECINCT                           29194 non-null  float64
 12  WARD PRECINCT                      36195 non-null  object
 13  POLICE DISTRICT                    31883 non-null  float64
 14  LICENSE CODE                       85895 non-null  int64
 15  LICENSE DESCRIPTION                85895 non-null  object
 16  LICENSE NUMBER                     85894 non-null  float64
 17  APPLICATION TYPE                   85895 non-null  object
 18  APPLICATION CREATED DATE           21235 non-null  datetime64[ns]
 19  APPLICATION REQUIREMENTS COMPLETE  85681 non-null  datetime64[ns]
 20  PAYMENT DATE                       84606 non-null  datetime64[ns]
 21  CONDITIONAL APPROVAL               85895 non-null  object
 22  LICENSE TERM START DATE            85667 non-null  datetime64[ns]
 23  LICENSE TERM EXPIRATION DATE       85877 non-null  datetime64[ns]
 24  LICENSE APPROVED FOR ISSUANCE      79106 non-null  datetime64[ns]
 25  DATE ISSUED                        85895 non-null  datetime64[ns]
 26  LICENSE STATUS CHANGE DATE         30495 non-null  datetime64[ns]
 27  SSA                                9449 non-null   float64
 28  LATITUDE                           38649 non-null  float64
 29  LONGITUDE                          38649 non-null  float64
 30  LOCATION                           38649 non-null  object
 31  LICENSE STATUS                     85895 non-null  object
dtypes: datetime64[ns](8), float64(7), int64(4), object(13)
memory usage: 21.0+ MB

In [9]:
df.isnull().sum()

ID                                       0
LICENSE ID                               0
ACCOUNT NUMBER                           0
SITE NUMBER                              0
LEGAL NAME                               0
DOING BUSINESS AS NAME                   1
ADDRESS                                  0
CITY                                     0
STATE                                    0
ZIP CODE                                31
WARD                                 49701
PRECINCT                             56701
WARD PRECINCT                        49700
POLICE DISTRICT                      54012
LICENSE CODE                             0
LICENSE DESCRIPTION                      0
LICENSE NUMBER                           1
APPLICATION TYPE                         0
APPLICATION CREATED DATE             64660
APPLICATION REQUIREMENTS COMPLETE      214
PAYMENT DATE                          1289
CONDITIONAL APPROVAL                     0
LICENSE TERM START DATE                228
LICENSE TERM EXPIRATION DATE            18
LICENSE APPROVED FOR ISSUANCE         6789
DATE ISSUED                              0
LICENSE STATUS CHANGE DATE           55400
SSA                                  76446
LATITUDE                             47246
LONGITUDE                            47246
LOCATION                             47246
LICENSE STATUS                           0
dtype: int64

In [11]:
df['LICENSE STATUS'].value_counts()

AAI    55400
AAC    30200
REV      290
REA        3
INQ        2
Name: LICENSE STATUS, dtype: int64

In [18]:
df[(df['LICENSE STATUS'] =='REA') | (df['LICENSE STATUS'] =='INQ')]

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS
6284,15990-20101216,2061140,6802,1,"S. A. A. ENTERPRISES, INC.",S. A. A. FOOD & LIQUORS,2561 E 75TH ST 1,CHICAGO,IL,60649,7.0,28.0,7-28,4.0,1006,Retail Food Establishment,15990.0,RENEW,NaT,2010-10-15,2010-12-14,N,2010-12-16,2012-12-15,2010-12-14,2010-12-14,2012-08-17,49.0,41.758940,-87.561645,"{'latitude': '41.758939922801', 'longitude': '...",REA
50757,1331913-20030929,1331913,249850,2,TURIN BUILDERS INC,TURIN BUILDERS INC,1343 S WASHINGTON,PARK RIDGE,IL,60068,NaN,NaN,NaN,NaN,1010,Limited Business License,1331913.0,ISSUE,2003-01-22,2003-09-29,NaT,N,2003-09-29,2004-02-15,2003-07-21,2003-07-22,2003-09-29,NaN,NaN,NaN,NaN,INQ
59549,1963143-20100816,2041316,341709,1,SAAN & BAADA CORP.,SERENITY SPA,7222 N HARLEM AVE 1,CHICAGO,IL,60631,41.0,1.0,41-1,16.0,1524,Massage Establishment,1963143.0,RENEW,NaT,2010-06-15,2010-08-02,N,2010-08-16,2012-08-15,2010-08-02,2010-08-03,2011-06-16,NaN,42.012424,-87.806777,"{'latitude': '42.01242416969208', 'longitude':...",REA
80153,1331914-20030929,1331914,249850,2,TURIN BUILDERS INC,TURIN BUILDERS INC,1343 S WASHINGTON,PARK RIDGE,IL,60068,NaN,NaN,NaN,NaN,1011,Home Repair,1331914.0,ISSUE,2003-01-22,2003-09-29,NaT,N,2003-09-29,2004-02-15,2003-07-21,2003-07-22,2003-09-29,NaN,NaN,NaN,NaN,INQ
82318,35093-20101216,2061724,32745,1,"2953 W. BELMONT, INC.",CANOS VILLAGE,2953 W BELMONT AVE,CHICAGO,IL,60618.0,33.0,13.0,33-13,14.0,1472,Music and Dance,35093.0,RENEW,NaT,2010-10-15,2010-12-07,N,2010-12-16,2012-12-15,2010-12-07,2010-12-08,2012-12-11,NaN,41.939255,-87.702427,"{'latitude': '41.939255035341795', 'longitude'...",REA

### encoding the column ""application create date

In [38]:
appl_creat_date=[]
for x in df['APPLICATION CREATED DATE']:
    if type(x)==pd._libs.tslibs.nattype.NaTType:
        appl_creat_date.append(0)
    else:    
        appl_creat_date.append(1)

In [35]:
type(df['APPLICATION CREATED DATE'][0])

pandas._libs.tslibs.nattype.NaTType

In [40]:
df['APPLICATION CREATE DATE ENCODED']=appl_creat_date

NameError: name 'DF' is not defined

### encoding the column "application requirement complete"

In [43]:
appl_req_complete=[]
for x in df['APPLICATION REQUIREMENTS COMPLETE']:
    if type(x)==pd._libs.tslibs.nattype.NaTType:
        appl_req_complete.append(0)
    else:    
        appl_req_complete.append(1)
df['APPLICATION REQUEST COMPLETE ENCODED']=appl_req_complete
df

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED
0,35342-20020816,1256593,32811,1,CARMEN CAHUE,CLAUDIA'S BRIDAL SHOP,2625 S CENTRAL PARK AVE 1,CHICAGO,IL,60623.0,22.0,28.0,22-28,10.0,1010,Limited Business License,35342.0,RENEW,NaT,2002-06-28,2002-08-21,N,2002-08-16,2003-08-15,2002-08-21,2006-04-11,NaT,25.0,41.843613,-87.714618,"{'latitude': '41.843612879431845', 'longitude'...",AAI,0,1
1,1358463-20051116,1639294,262311,29,"ISLA TROPICAL, INC.",ISLA TROPICAL,2825 W MONTROSE AVE,CHICAGO,IL,60618,33.0,23.0,33-23,17.0,1315,Mobile Food Dispenser,1358463.0,RENEW,NaT,2005-09-22,2005-11-03,N,2005-11-16,2006-11-15,2006-04-05,2006-06-12,2006-06-15,60.0,41.961132,-87.699626,"{'latitude': '41.96113244107215', 'longitude':...",AAC,0,1
2,1980233-20090722,1980233,345008,1,DJS REMODELING,"DJS REMODELING, INC.",1605 CLAVEY RD 1,HIGHLAND,IL,60035,NaN,NaN,NaN,NaN,1011,Home Repair,1980233.0,ISSUE,2009-06-29,2009-07-22,2009-07-22,N,2009-07-22,2011-07-15,2009-07-22,2009-07-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1
3,1476582-20040211,1476582,273121,1,ALL-BRY CONSTRUCTION CO.,ALL-BRY CONSTRUCTION CO.,8 NORTH TRAIL,LEMONT,IL,60439,NaN,NaN,NaN,NaN,1010,Limited Business License,1476582.0,ISSUE,2004-02-10,2004-02-10,2004-02-10,N,2004-02-11,2005-02-15,2004-02-10,2004-02-11,NaT,NaN,NaN,NaN,NaN,AAI,1,1
4,1141408-20080516,1896750,213785,1,MCDONOUGH MECHANICAL SERVICE,MCDONOUGH MECHANICAL SERVICE,4081 JOSEPH DR,WAUKEGAN,IL,60087,NaN,NaN,NaN,NaN,1010,Limited Business License,1141408.0,RENEW,NaT,2008-03-24,2008-06-04,N,2008-05-16,2010-05-15,2008-06-04,2008-06-05,NaT,NaN,NaN,NaN,NaN,AAI,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85890,12652-20120516,2143400,8011,1,UNITED PARCEL SERVICE,UNITED PARCEL SERVICE,1400 S JEFFERSON ST,CHICAGO,IL,60607.0,11.0,28.0,11-28,1.0,1008,Hazardous Materials,12652.0,RENEW,NaT,2012-03-15,2012-05-07,N,2012-05-16,2014-05-15,2012-05-07,2012-05-08,2012-12-29,NaN,41.863501,-87.642210,"{'latitude': '41.86350135244771', 'longitude':...",AAC,0,1
85891,1821421-20070522,1821421,317725,1,"EXPRESS BOARD UP SERVICE, INC.","EXPRESS BOARD UP SERVICE, INC.",8707 VANGUARD DR,MACHESNEY PARK,IL,61115.0,NaN,NaN,NaN,NaN,1800,Board-Up Work,1821421.0,ISSUE,2007-05-21,2007-05-22,2007-05-22,N,2007-05-22,2009-06-15,2007-05-22,2007-05-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1
85892,74137-20090116,1939358,8458,2,ARAMARK SMMS LLC,ARAMARK FACILITY SERVICES,2300 WARRENVILLE RD 1ST,DOWNERS GROVE,IL,60515.0,NaN,NaN,NaN,NaN,1010,Limited Business License,74137.0,RENEW,NaT,2008-11-14,2009-01-09,N,2009-01-16,2011-01-15,2009-01-09,2009-12-08,NaT,NaN,NaN,NaN,NaN,AAI,0,1
85893,2049545-20111016,2110060,2156,43,GENERAL NUTRITION CORPORATION,GENERAL NUTRITION CENTER # 61,5151 S PULASKI RD SLAB ON GRADE T-21,CHICAGO,IL,60632.0,23.0,NaN,23-,NaN,1010,Limited Business License,2049545.0,RENEW,NaT,2011-08-15,2011-10-03,N,2011-10-16,2013-10-15,2011-10-03,2011-10-11,2012-05-08,NaN,41.799012,-87.723181,"{'latitude': '41.79901235310339', 'longitude':...",AAC,0,1
85894,1070196-20040216,1461628,205936,1,JUAN CARLOS ERAZO,CASA DE JUAN RESTAURANT,5814 W FULLERTON AVE,CHICAGO,IL,60639.0,30.0,52.0,30-52,25.0,1006,Retail Food Establishment,1070196.0,RENEW,NaT,2003-12-15,2004-02-06,N,2004-02-16,2005-02-15,2003-12-22,2004-02-09,2005-01-07,NaN,41.924004,-87.771507,"{'latitude': '41.92400390449922', 'longitude':...",AAC,0,1

### encoding the column "payment date"

In [44]:
payment_date=[]
for x in df['PAYMENT DATE']:
    if type(x)==pd._libs.tslibs.nattype.NaTType:
        payment_date.append(0)
    else:    
        payment_date.append(1)
df['PAYMENT DATE ENCODED']=payment_date
df

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED
0,35342-20020816,1256593,32811,1,CARMEN CAHUE,CLAUDIA'S BRIDAL SHOP,2625 S CENTRAL PARK AVE 1,CHICAGO,IL,60623.0,22.0,28.0,22-28,10.0,1010,Limited Business License,35342.0,RENEW,NaT,2002-06-28,2002-08-21,N,2002-08-16,2003-08-15,2002-08-21,2006-04-11,NaT,25.0,41.843613,-87.714618,"{'latitude': '41.843612879431845', 'longitude'...",AAI,0,1,1
1,1358463-20051116,1639294,262311,29,"ISLA TROPICAL, INC.",ISLA TROPICAL,2825 W MONTROSE AVE,CHICAGO,IL,60618,33.0,23.0,33-23,17.0,1315,Mobile Food Dispenser,1358463.0,RENEW,NaT,2005-09-22,2005-11-03,N,2005-11-16,2006-11-15,2006-04-05,2006-06-12,2006-06-15,60.0,41.961132,-87.699626,"{'latitude': '41.96113244107215', 'longitude':...",AAC,0,1,1
2,1980233-20090722,1980233,345008,1,DJS REMODELING,"DJS REMODELING, INC.",1605 CLAVEY RD 1,HIGHLAND,IL,60035,NaN,NaN,NaN,NaN,1011,Home Repair,1980233.0,ISSUE,2009-06-29,2009-07-22,2009-07-22,N,2009-07-22,2011-07-15,2009-07-22,2009-07-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1
3,1476582-20040211,1476582,273121,1,ALL-BRY CONSTRUCTION CO.,ALL-BRY CONSTRUCTION CO.,8 NORTH TRAIL,LEMONT,IL,60439,NaN,NaN,NaN,NaN,1010,Limited Business License,1476582.0,ISSUE,2004-02-10,2004-02-10,2004-02-10,N,2004-02-11,2005-02-15,2004-02-10,2004-02-11,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1
4,1141408-20080516,1896750,213785,1,MCDONOUGH MECHANICAL SERVICE,MCDONOUGH MECHANICAL SERVICE,4081 JOSEPH DR,WAUKEGAN,IL,60087,NaN,NaN,NaN,NaN,1010,Limited Business License,1141408.0,RENEW,NaT,2008-03-24,2008-06-04,N,2008-05-16,2010-05-15,2008-06-04,2008-06-05,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85890,12652-20120516,2143400,8011,1,UNITED PARCEL SERVICE,UNITED PARCEL SERVICE,1400 S JEFFERSON ST,CHICAGO,IL,60607.0,11.0,28.0,11-28,1.0,1008,Hazardous Materials,12652.0,RENEW,NaT,2012-03-15,2012-05-07,N,2012-05-16,2014-05-15,2012-05-07,2012-05-08,2012-12-29,NaN,41.863501,-87.642210,"{'latitude': '41.86350135244771', 'longitude':...",AAC,0,1,1
85891,1821421-20070522,1821421,317725,1,"EXPRESS BOARD UP SERVICE, INC.","EXPRESS BOARD UP SERVICE, INC.",8707 VANGUARD DR,MACHESNEY PARK,IL,61115.0,NaN,NaN,NaN,NaN,1800,Board-Up Work,1821421.0,ISSUE,2007-05-21,2007-05-22,2007-05-22,N,2007-05-22,2009-06-15,2007-05-22,2007-05-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1
85892,74137-20090116,1939358,8458,2,ARAMARK SMMS LLC,ARAMARK FACILITY SERVICES,2300 WARRENVILLE RD 1ST,DOWNERS GROVE,IL,60515.0,NaN,NaN,NaN,NaN,1010,Limited Business License,74137.0,RENEW,NaT,2008-11-14,2009-01-09,N,2009-01-16,2011-01-15,2009-01-09,2009-12-08,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1
85893,2049545-20111016,2110060,2156,43,GENERAL NUTRITION CORPORATION,GENERAL NUTRITION CENTER # 61,5151 S PULASKI RD SLAB ON GRADE T-21,CHICAGO,IL,60632.0,23.0,NaN,23-,NaN,1010,Limited Business License,2049545.0,RENEW,NaT,2011-08-15,2011-10-03,N,2011-10-16,2013-10-15,2011-10-03,2011-10-11,2012-05-08,NaN,41.799012,-87.723181,"{'latitude': '41.79901235310339', 'longitude':...",AAC,0,1,1
85894,1070196-20040216,1461628,205936,1,JUAN CARLOS ERAZO,CASA DE JUAN RESTAURANT,5814 W FULLERTON AVE,CHICAGO,IL,60639.0,30.0,52.0,30-52,25.0,1006,Retail Food Establishment,1070196.0,RENEW,NaT,2003-12-15,2004-02-06,N,2004-02-16,2005-02-15,2003-12-22,2004-02-09,2005-01-07,NaN,41.924004,-87.771507,"{'latitude': '41.92400390449922', 'longitude':...",AAC,0,1,1

### encoding the column "license term start date"

In [45]:
license_term_start=[]
for x in df['LICENSE TERM START DATE']:
    if type(x)==pd._libs.tslibs.nattype.NaTType:
        license_term_start.append(0)
    else:    
        license_term_start.append(1)
df['LICENSE TERM START DATE ENCODED']=license_term_start
df

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED
0,35342-20020816,1256593,32811,1,CARMEN CAHUE,CLAUDIA'S BRIDAL SHOP,2625 S CENTRAL PARK AVE 1,CHICAGO,IL,60623.0,22.0,28.0,22-28,10.0,1010,Limited Business License,35342.0,RENEW,NaT,2002-06-28,2002-08-21,N,2002-08-16,2003-08-15,2002-08-21,2006-04-11,NaT,25.0,41.843613,-87.714618,"{'latitude': '41.843612879431845', 'longitude'...",AAI,0,1,1,1
1,1358463-20051116,1639294,262311,29,"ISLA TROPICAL, INC.",ISLA TROPICAL,2825 W MONTROSE AVE,CHICAGO,IL,60618,33.0,23.0,33-23,17.0,1315,Mobile Food Dispenser,1358463.0,RENEW,NaT,2005-09-22,2005-11-03,N,2005-11-16,2006-11-15,2006-04-05,2006-06-12,2006-06-15,60.0,41.961132,-87.699626,"{'latitude': '41.96113244107215', 'longitude':...",AAC,0,1,1,1
2,1980233-20090722,1980233,345008,1,DJS REMODELING,"DJS REMODELING, INC.",1605 CLAVEY RD 1,HIGHLAND,IL,60035,NaN,NaN,NaN,NaN,1011,Home Repair,1980233.0,ISSUE,2009-06-29,2009-07-22,2009-07-22,N,2009-07-22,2011-07-15,2009-07-22,2009-07-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1
3,1476582-20040211,1476582,273121,1,ALL-BRY CONSTRUCTION CO.,ALL-BRY CONSTRUCTION CO.,8 NORTH TRAIL,LEMONT,IL,60439,NaN,NaN,NaN,NaN,1010,Limited Business License,1476582.0,ISSUE,2004-02-10,2004-02-10,2004-02-10,N,2004-02-11,2005-02-15,2004-02-10,2004-02-11,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1
4,1141408-20080516,1896750,213785,1,MCDONOUGH MECHANICAL SERVICE,MCDONOUGH MECHANICAL SERVICE,4081 JOSEPH DR,WAUKEGAN,IL,60087,NaN,NaN,NaN,NaN,1010,Limited Business License,1141408.0,RENEW,NaT,2008-03-24,2008-06-04,N,2008-05-16,2010-05-15,2008-06-04,2008-06-05,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85890,12652-20120516,2143400,8011,1,UNITED PARCEL SERVICE,UNITED PARCEL SERVICE,1400 S JEFFERSON ST,CHICAGO,IL,60607.0,11.0,28.0,11-28,1.0,1008,Hazardous Materials,12652.0,RENEW,NaT,2012-03-15,2012-05-07,N,2012-05-16,2014-05-15,2012-05-07,2012-05-08,2012-12-29,NaN,41.863501,-87.642210,"{'latitude': '41.86350135244771', 'longitude':...",AAC,0,1,1,1
85891,1821421-20070522,1821421,317725,1,"EXPRESS BOARD UP SERVICE, INC.","EXPRESS BOARD UP SERVICE, INC.",8707 VANGUARD DR,MACHESNEY PARK,IL,61115.0,NaN,NaN,NaN,NaN,1800,Board-Up Work,1821421.0,ISSUE,2007-05-21,2007-05-22,2007-05-22,N,2007-05-22,2009-06-15,2007-05-22,2007-05-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1
85892,74137-20090116,1939358,8458,2,ARAMARK SMMS LLC,ARAMARK FACILITY SERVICES,2300 WARRENVILLE RD 1ST,DOWNERS GROVE,IL,60515.0,NaN,NaN,NaN,NaN,1010,Limited Business License,74137.0,RENEW,NaT,2008-11-14,2009-01-09,N,2009-01-16,2011-01-15,2009-01-09,2009-12-08,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1
85893,2049545-20111016,2110060,2156,43,GENERAL NUTRITION CORPORATION,GENERAL NUTRITION CENTER # 61,5151 S PULASKI RD SLAB ON GRADE T-21,CHICAGO,IL,60632.0,23.0,NaN,23-,NaN,1010,Limited Business License,2049545.0,RENEW,NaT,2011-08-15,2011-10-03,N,2011-10-16,2013-10-15,2011-10-03,2011-10-11,2012-05-08,NaN,41.799012,-87.723181,"{'latitude': '41.79901235310339', 'longitude':...",AAC,0,1,1,1
85894,1070196-20040216,1461628,205936,1,JUAN CARLOS ERAZO,CASA DE JUAN RESTAURANT,5814 W FULLERTON AVE,CHICAGO,IL,60639.0,30.0,52.0,30-52,25.0,1006,Retail Food Establishment,1070196.0,RENEW,NaT,2003-12-15,2004-02-06,N,2004-02-16,2005-02-15,2003-12-22,2004-02-09,2005-01-07,NaN,41.924004,-87.771507,"{'latitude': '41.92400390449922', 'longitude':...",AAC,0,1,1,1

### encoding the column "licensed approved"

In [47]:
license_approved=[]
for x in df['LICENSE APPROVED FOR ISSUANCE']:
    if type(x)==pd._libs.tslibs.nattype.NaTType:
        license_approved.append(0)
    else:    
        license_approved.append(1)
df['LICENSE APPROVED FOR ISSUANCE ENCODED']=license_approved
df

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED
0,35342-20020816,1256593,32811,1,CARMEN CAHUE,CLAUDIA'S BRIDAL SHOP,2625 S CENTRAL PARK AVE 1,CHICAGO,IL,60623.0,22.0,28.0,22-28,10.0,1010,Limited Business License,35342.0,RENEW,NaT,2002-06-28,2002-08-21,N,2002-08-16,2003-08-15,2002-08-21,2006-04-11,NaT,25.0,41.843613,-87.714618,"{'latitude': '41.843612879431845', 'longitude'...",AAI,0,1,1,1,1
1,1358463-20051116,1639294,262311,29,"ISLA TROPICAL, INC.",ISLA TROPICAL,2825 W MONTROSE AVE,CHICAGO,IL,60618,33.0,23.0,33-23,17.0,1315,Mobile Food Dispenser,1358463.0,RENEW,NaT,2005-09-22,2005-11-03,N,2005-11-16,2006-11-15,2006-04-05,2006-06-12,2006-06-15,60.0,41.961132,-87.699626,"{'latitude': '41.96113244107215', 'longitude':...",AAC,0,1,1,1,1
2,1980233-20090722,1980233,345008,1,DJS REMODELING,"DJS REMODELING, INC.",1605 CLAVEY RD 1,HIGHLAND,IL,60035,NaN,NaN,NaN,NaN,1011,Home Repair,1980233.0,ISSUE,2009-06-29,2009-07-22,2009-07-22,N,2009-07-22,2011-07-15,2009-07-22,2009-07-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1
3,1476582-20040211,1476582,273121,1,ALL-BRY CONSTRUCTION CO.,ALL-BRY CONSTRUCTION CO.,8 NORTH TRAIL,LEMONT,IL,60439,NaN,NaN,NaN,NaN,1010,Limited Business License,1476582.0,ISSUE,2004-02-10,2004-02-10,2004-02-10,N,2004-02-11,2005-02-15,2004-02-10,2004-02-11,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1
4,1141408-20080516,1896750,213785,1,MCDONOUGH MECHANICAL SERVICE,MCDONOUGH MECHANICAL SERVICE,4081 JOSEPH DR,WAUKEGAN,IL,60087,NaN,NaN,NaN,NaN,1010,Limited Business License,1141408.0,RENEW,NaT,2008-03-24,2008-06-04,N,2008-05-16,2010-05-15,2008-06-04,2008-06-05,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85890,12652-20120516,2143400,8011,1,UNITED PARCEL SERVICE,UNITED PARCEL SERVICE,1400 S JEFFERSON ST,CHICAGO,IL,60607.0,11.0,28.0,11-28,1.0,1008,Hazardous Materials,12652.0,RENEW,NaT,2012-03-15,2012-05-07,N,2012-05-16,2014-05-15,2012-05-07,2012-05-08,2012-12-29,NaN,41.863501,-87.642210,"{'latitude': '41.86350135244771', 'longitude':...",AAC,0,1,1,1,1
85891,1821421-20070522,1821421,317725,1,"EXPRESS BOARD UP SERVICE, INC.","EXPRESS BOARD UP SERVICE, INC.",8707 VANGUARD DR,MACHESNEY PARK,IL,61115.0,NaN,NaN,NaN,NaN,1800,Board-Up Work,1821421.0,ISSUE,2007-05-21,2007-05-22,2007-05-22,N,2007-05-22,2009-06-15,2007-05-22,2007-05-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1
85892,74137-20090116,1939358,8458,2,ARAMARK SMMS LLC,ARAMARK FACILITY SERVICES,2300 WARRENVILLE RD 1ST,DOWNERS GROVE,IL,60515.0,NaN,NaN,NaN,NaN,1010,Limited Business License,74137.0,RENEW,NaT,2008-11-14,2009-01-09,N,2009-01-16,2011-01-15,2009-01-09,2009-12-08,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1,1
85893,2049545-20111016,2110060,2156,43,GENERAL NUTRITION CORPORATION,GENERAL NUTRITION CENTER # 61,5151 S PULASKI RD SLAB ON GRADE T-21,CHICAGO,IL,60632.0,23.0,NaN,23-,NaN,1010,Limited Business License,2049545.0,RENEW,NaT,2011-08-15,2011-10-03,N,2011-10-16,2013-10-15,2011-10-03,2011-10-11,2012-05-08,NaN,41.799012,-87.723181,"{'latitude': '41.79901235310339', 'longitude':...",AAC,0,1,1,1,1
85894,1070196-20040216,1461628,205936,1,JUAN CARLOS ERAZO,CASA DE JUAN RESTAURANT,5814 W FULLERTON AVE,CHICAGO,IL,60639.0,30.0,52.0,30-52,25.0,1006,Retail Food Establishment,1070196.0,RENEW,NaT,2003-12-15,2004-02-06,N,2004-02-16,2005-02-15,2003-12-22,2004-02-09,2005-01-07,NaN,41.924004,-87.771507,"{'latitude': '41.92400390449922', 'longitude':...",AAC,0,1,1,1,1

### encoding the column "license status change"

In [48]:
license_status_change=[]
for x in df['LICENSE STATUS CHANGE DATE']:
    if type(x)==pd._libs.tslibs.nattype.NaTType:
        license_status_change.append(0)
    else:    
        license_status_change.append(1)
df['LICENSE STATUS CHANGE DATE ENCODED']=license_status_change
df

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED,LICENSE STATUS CHANGE DATE ENCODED
0,35342-20020816,1256593,32811,1,CARMEN CAHUE,CLAUDIA'S BRIDAL SHOP,2625 S CENTRAL PARK AVE 1,CHICAGO,IL,60623.0,22.0,28.0,22-28,10.0,1010,Limited Business License,35342.0,RENEW,NaT,2002-06-28,2002-08-21,N,2002-08-16,2003-08-15,2002-08-21,2006-04-11,NaT,25.0,41.843613,-87.714618,"{'latitude': '41.843612879431845', 'longitude'...",AAI,0,1,1,1,1,0
1,1358463-20051116,1639294,262311,29,"ISLA TROPICAL, INC.",ISLA TROPICAL,2825 W MONTROSE AVE,CHICAGO,IL,60618,33.0,23.0,33-23,17.0,1315,Mobile Food Dispenser,1358463.0,RENEW,NaT,2005-09-22,2005-11-03,N,2005-11-16,2006-11-15,2006-04-05,2006-06-12,2006-06-15,60.0,41.961132,-87.699626,"{'latitude': '41.96113244107215', 'longitude':...",AAC,0,1,1,1,1,1
2,1980233-20090722,1980233,345008,1,DJS REMODELING,"DJS REMODELING, INC.",1605 CLAVEY RD 1,HIGHLAND,IL,60035,NaN,NaN,NaN,NaN,1011,Home Repair,1980233.0,ISSUE,2009-06-29,2009-07-22,2009-07-22,N,2009-07-22,2011-07-15,2009-07-22,2009-07-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0
3,1476582-20040211,1476582,273121,1,ALL-BRY CONSTRUCTION CO.,ALL-BRY CONSTRUCTION CO.,8 NORTH TRAIL,LEMONT,IL,60439,NaN,NaN,NaN,NaN,1010,Limited Business License,1476582.0,ISSUE,2004-02-10,2004-02-10,2004-02-10,N,2004-02-11,2005-02-15,2004-02-10,2004-02-11,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0
4,1141408-20080516,1896750,213785,1,MCDONOUGH MECHANICAL SERVICE,MCDONOUGH MECHANICAL SERVICE,4081 JOSEPH DR,WAUKEGAN,IL,60087,NaN,NaN,NaN,NaN,1010,Limited Business License,1141408.0,RENEW,NaT,2008-03-24,2008-06-04,N,2008-05-16,2010-05-15,2008-06-04,2008-06-05,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85890,12652-20120516,2143400,8011,1,UNITED PARCEL SERVICE,UNITED PARCEL SERVICE,1400 S JEFFERSON ST,CHICAGO,IL,60607.0,11.0,28.0,11-28,1.0,1008,Hazardous Materials,12652.0,RENEW,NaT,2012-03-15,2012-05-07,N,2012-05-16,2014-05-15,2012-05-07,2012-05-08,2012-12-29,NaN,41.863501,-87.642210,"{'latitude': '41.86350135244771', 'longitude':...",AAC,0,1,1,1,1,1
85891,1821421-20070522,1821421,317725,1,"EXPRESS BOARD UP SERVICE, INC.","EXPRESS BOARD UP SERVICE, INC.",8707 VANGUARD DR,MACHESNEY PARK,IL,61115.0,NaN,NaN,NaN,NaN,1800,Board-Up Work,1821421.0,ISSUE,2007-05-21,2007-05-22,2007-05-22,N,2007-05-22,2009-06-15,2007-05-22,2007-05-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0
85892,74137-20090116,1939358,8458,2,ARAMARK SMMS LLC,ARAMARK FACILITY SERVICES,2300 WARRENVILLE RD 1ST,DOWNERS GROVE,IL,60515.0,NaN,NaN,NaN,NaN,1010,Limited Business License,74137.0,RENEW,NaT,2008-11-14,2009-01-09,N,2009-01-16,2011-01-15,2009-01-09,2009-12-08,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1,1,0
85893,2049545-20111016,2110060,2156,43,GENERAL NUTRITION CORPORATION,GENERAL NUTRITION CENTER # 61,5151 S PULASKI RD SLAB ON GRADE T-21,CHICAGO,IL,60632.0,23.0,NaN,23-,NaN,1010,Limited Business License,2049545.0,RENEW,NaT,2011-08-15,2011-10-03,N,2011-10-16,2013-10-15,2011-10-03,2011-10-11,2012-05-08,NaN,41.799012,-87.723181,"{'latitude': '41.79901235310339', 'longitude':...",AAC,0,1,1,1,1,1
85894,1070196-20040216,1461628,205936,1,JUAN CARLOS ERAZO,CASA DE JUAN RESTAURANT,5814 W FULLERTON AVE,CHICAGO,IL,60639.0,30.0,52.0,30-52,25.0,1006,Retail Food Establishment,1070196.0,RENEW,NaT,2003-12-15,2004-02-06,N,2004-02-16,2005-02-15,2003-12-22,2004-02-09,2005-01-07,NaN,41.924004,-87.771507,"{'latitude': '41.92400390449922', 'longitude':...",AAC,0,1,1,1,1,1

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85895 entries, 0 to 85894
Data columns (total 38 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   ID                                     85895 non-null  object
 1   LICENSE ID                             85895 non-null  int64
 2   ACCOUNT NUMBER                         85895 non-null  int64
 3   SITE NUMBER                            85895 non-null  int64
 4   LEGAL NAME                             85895 non-null  object
 5   DOING BUSINESS AS NAME                 85894 non-null  object
 6   ADDRESS                                85895 non-null  object
 7   CITY                                   85895 non-null  object
 8   STATE                                  85895 non-null  object
 9   ZIP CODE                               85864 non-null  object
 10  WARD                                   36194 non-null  float64
 11  PRECINCT                               29194 non-null  float64
 12  WARD PRECINCT                          36195 non-null  object
 13  POLICE DISTRICT                        31883 non-null  float64
 14  LICENSE CODE                           85895 non-null  int64
 15  LICENSE DESCRIPTION                    85895 non-null  object
 16  LICENSE NUMBER                         85894 non-null  float64
 17  APPLICATION TYPE                       85895 non-null  object
 18  APPLICATION CREATED DATE               21235 non-null  datetime64[ns]
 19  APPLICATION REQUIREMENTS COMPLETE      85681 non-null  datetime64[ns]
 20  PAYMENT DATE                           84606 non-null  datetime64[ns]
 21  CONDITIONAL APPROVAL                   85895 non-null  object
 22  LICENSE TERM START DATE                85667 non-null  datetime64[ns]
 23  LICENSE TERM EXPIRATION DATE           85877 non-null  datetime64[ns]
 24  LICENSE APPROVED FOR ISSUANCE          79106 non-null  datetime64[ns]
 25  DATE ISSUED                            85895 non-null  datetime64[ns]
 26  LICENSE STATUS CHANGE DATE             30495 non-null  datetime64[ns]
 27  SSA                                    9449 non-null   float64
 28  LATITUDE                               38649 non-null  float64
 29  LONGITUDE                              38649 non-null  float64
 30  LOCATION                               38649 non-null  object
 31  LICENSE STATUS                         85895 non-null  object
 32  APPLICATION CREATE DATE ENCODED        85895 non-null  int64
 33  APPLICATION REQUEST COMPLETE ENCODED   85895 non-null  int64
 34  PAYMENT DATE ENCODED                   85895 non-null  int64
 35  LICENSE TERM START DATE ENCODED        85895 non-null  int64
 36  LICENSE APPROVED FOR ISSUANCE ENCODED  85895 non-null  int64
 37  LICENSE STATUS CHANGE DATE ENCODED     85895 non-null  int64
dtypes: datetime64[ns](8), float64(7), int64(10), object(13)
memory usage: 24.9+ MB

In [55]:
df[df['DOING BUSINESS AS NAME'].isnull()==True]

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED,LICENSE STATUS CHANGE DATE ENCODED
9114,2146523-20120326,2146523,370691,1,3 MB REMODELING CORP,NaN,607 N OAK AVE,AURORA,IL,60506,NaN,NaN,NaN,NaN,1011,Home Repair,2146523.0,ISSUE,NaT,2012-03-21,2012-03-24,N,2012-03-26,2014-04-15,2012-03-24,2012-03-26,2012-12-29,NaN,NaN,NaN,NaN,AAC,0,1,1,1,1,1

In [58]:
df[df['CONDITIONAL APPROVAL']=='Y']

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED,LICENSE STATUS CHANGE DATE ENCODED
5307,1193450-20020401,1193450,219921,1,"FORTUNATO, LLC",ADOBO GRILL,2005-2007 W DIVISION ST,CHICAGO,IL,60622.0,1.0,3.0,1-3,12.0,1006,Retail Food Establishment,1193450.0,ISSUE,2001-10-15,2001-12-21,2001-12-21,Y,2002-04-01,2002-11-15,2002-04-01,2002-04-02,2010-09-27,33.0,41.903077,-87.677528,"{'latitude': '41.903076748534474', 'longitude'...",AAC,1,1,1,1,1,1
13871,1979963-20100521,1979963,344863,1,"JIMMY GREENS, LLC",JIMMY GREEN'S,825 S STATE ST 1ST,CHICAGO,IL,60605,4.0,58.0,4-58,1.0,1006,Retail Food Establishment,1979963.0,ISSUE,2009-06-24,2009-11-16,2009-11-16,Y,2010-05-21,2012-06-15,2010-05-21,2010-05-21,2012-10-26,NaN,41.871464,-87.627369,"{'latitude': '41.87146433662049', 'longitude':...",AAC,1,1,1,1,1,1
14794,1517146-20050825,1517146,280339,1,"SAGE, INC.",SAGE,2463-2465 N CLARK ST,CHICAGO,IL,60614.0,43.0,27.0,43-27,19.0,1006,Retail Food Establishment,1517146.0,ISSUE,2004-08-12,2005-04-28,2005-04-28,Y,2005-08-25,2006-05-15,2005-08-24,2005-08-25,2007-07-17,23.0,41.927218,-87.641298,"{'latitude': '41.92721836470902', 'longitude':...",AAC,1,1,1,1,1,1
27751,1920838-20100201,1920838,334474,1,"REVOLUTION BREWING, LLC",REVOLUTION BREWING,2323 N MILWAUKEE AVE 1ST,CHICAGO,IL,60647.0,1.0,10.0,1-10,14.0,1006,Retail Food Establishment,1920838.0,ISSUE,2008-07-16,2008-12-10,2008-12-10,Y,2010-02-01,2011-11-15,2010-02-01,2010-02-01,2011-07-25,NaN,41.923532,-87.698140,"{'latitude': '41.92353245816767', 'longitude':...",AAC,1,1,1,1,1,1
28574,2031975-20101206,2031975,352793,1,MINGHIN CUISINE LLC,MINGHIN CUISINE,2168-2170 S ARCHER AVE 1-2,CHICAGO,IL,60616,25.0,16.0,25-16,9.0,1475,Consumption on Premises - Incidental Activity,2031975.0,ISSUE,2010-04-26,2010-10-05,2010-09-10,Y,2010-12-06,2012-12-15,2010-12-06,2010-12-06,2012-02-28,NaN,41.853167,-87.634461,"{'latitude': '41.85316719933144', 'longitude':...",AAC,1,1,1,1,1,1
36820,1884482-20090210,1884482,326151,1,"ASIA ON ILLINOIS, LLC",SUNDA,110 W ILLINOIS ST 1,CHICAGO,IL,60610,42.0,46.0,42-46,18.0,1006,Retail Food Establishment,1884482.0,ISSUE,2008-01-09,2008-03-26,2008-03-26,Y,2009-02-10,2010-02-15,2009-02-09,2009-02-09,2009-12-04,NaN,41.890924,-87.631618,"{'latitude': '41.890924221316645', 'longitude'...",AAC,1,1,1,1,1,1
41669,1884483-20090223,1884483,326151,1,"ASIA ON ILLINOIS, LLC",SUNDA,110 W ILLINOIS ST 1,CHICAGO,IL,60610,42.0,46.0,42-46,18.0,1475,Consumption on Premises - Incidental Activity,1884483.0,ISSUE,2008-01-09,2008-04-23,2008-03-26,Y,2009-02-23,2010-02-15,2009-02-23,2009-02-23,2009-12-04,NaN,41.890924,-87.631618,"{'latitude': '41.890924221316645', 'longitude'...",AAC,1,1,1,1,1,1
52326,1598382-20060530,1598382,292957,1,"THE BIG FOUR, LLC",HAMBURGER MARY'S CHICAGO,5400 N CLARK ST,CHICAGO,IL,60640,40.0,42.0,40-42,20.0,1475,Consumption on Premises - Incidental Activity,1598382.0,ISSUE,2005-06-20,2006-01-31,2006-01-30,Y,2006-05-30,2006-08-15,2006-05-30,2006-05-30,2009-07-16,22.0,41.979884,-87.668429,"{'latitude': '41.97988428297559', 'longitude':...",AAC,1,1,1,1,1,1
56770,1804256-20091218,1804256,315299,1,"3756-58 W. NORTH, INC.","3756-58 W. NORTH, INC.",3756-3758 W NORTH AVE 1,CHICAGO,IL,60647.0,26.0,11.0,26-11,25.0,1475,Consumption on Premises - Incidental Activity,1804256.0,ISSUE,2007-03-19,2007-10-22,2007-09-24,Y,2009-12-18,2011-11-15,2009-12-18,2009-12-18,2010-05-17,NaN,41.910052,-87.721316,"{'latitude': '41.91005174981479', 'longitude':...",AAC,1,1,1,1,1,1
59610,2003678-20100818,2003678,348510,1,CHIKURIN INC.,CHIKURIN,1811 W NORTH AVE 1ST 103,CHICAGO,IL,60622.0,2.0,21.0,2-21,14.0,1475,Consumption on Premises - Incidental Activity,2003678.0,ISSUE,2009-10-30,2010-05-04,2010-05-04,Y,2010-08-18,2012-08-15,2010-07-23,2010-07-23,2011-09-19,33.0,41.910444,-87.673057,"{'latitude': '41.9104439540635', 'longitude': ...",AAC,1,1,1,1,1,1
60752,2084243-20110617,2084243,360180,1,"MARGARITAVILLE OF CHICAGO, LLC",JIMMY BUFFETT'S MARGARITAVILLE BAR & GRILL,600 E GRAND AVE,CHICAGO,IL,60611,42.0,11.0,42-11,18.0,1479,Navy Pier - Outdoor Fixed,2084243.0,ISSUE,2011-03-01,2011-04-05,2011-03-18,Y,2011-06-17,2013-07-15,2011-06-17,2011-06-17,2012-06-18,NaN,41.892094,-87.611570,"{'latitude': '41.892094136861786', 'longitude'...",AAC,1,1,1,1,1,1
67113,1579281-20051109,1579281,288873,1,"PREMIUM THEMES, INC.",Red Ivy,3519-3525 N CLARK ST,CHICAGO,IL,60657,44.0,31.0,44-31,19.0,1006,Retail Food Establishment,1579281.0,ISSUE,2005-03-14,2005-08-02,2005-08-02,Y,2005-11-09,2006-02-15,2005-11-08,2005-11-09,2008-12-04,17.0,41.946281,-87.655603,"{'latitude': '41.94628081101039', 'longitude':...",AAC,1,1,1,1,1,1
69200,2108543-20120730,2108543,362918,2,"NDE RESTAURANT VENTURES, LLC",ALAIN'S RESTAURANT,1355 S MICHIGAN AVE 1,CHICAGO,IL,60605,3.0,60.0,3-60,1.0,1475,Consumption on Premises - Incidental Activity,2108543.0,ISSUE,2011-07-25,2011-11-09,2011-10-14,Y,2012-07-30,2014-08-15,2012-07-30,2012-07-30,2012-11-21,NaN,41.864249,-87.623934,"{'latitude': '41.864248796634286', 'longitude'...",AAC,1,1,1,1,1,1
75360,1579282-20051116,1579282,288873,1,"PREMIUM THEMES, INC.",Red Ivy,3519-3525 N CLARK ST,CHICAGO,IL,60657,44.0,31.0,44-31,19.0,1475,Consumption on Premises - Incidental Activity,1579282.0,ISSUE,2005-03-14,2005-08-02,2005-08-02,Y,2005-11-16,2006-02-15,2005-11-16,2005-11-16,2008-12-04,17.0,41.946281,-87.655603,"{'latitude': '41.94628081101039', 'longitude':...",AAC,1,1,1,1,1,1
79412,1820164-20080422,1820164,317186,1,205 N. PEORIA INC.,CLUB ROYALE,205 N PEORIA ST 1,CHICAGO,IL,60607,27.0,1.0,27-1,12.0,1006,Retail Food Establishment,1820164.0,ISSUE,2007-05-07,2007-08-20,2007-08-20,Y,2008-04-22,2010-05-15,2008-04-21,2008-04-22,2009-03-25,NaN,41.885815,-87.649667,"{'latitude': '41.88581503908056', 'longitude':...",AAC,1,1,1,1,1,1
80578,1766708-20080407,1766708,309621,1,HP RESTAURANT VENTURES L.L.C.,PARK 52,5201 S HARPER AVE 1 WEST,CHICAGO,IL,60615,4.0,47.0,4-47,2.0,1006,Retail Food Establishment,1766708.0,ISSUE,2006-09-29,2006-11-06,2006-11-06,Y,2008-04-07,2008-06-15,2008-04-07,2008-04-07,2011-06-14,61.0,41.801062,-87.588993,"{'latitude': '41.80106220163419', 'longitude':...",AAC,1,1,1,1,1,1
82684,1381575-20040426,1381575,265878,1,ZENGO CAFFE INC.,TURQUOISE CAFE,2147 W ROSCOE ST,CHICAGO,IL,60618.0,32.0,15.0,32-15,19.0,1006,Retail Food Establishment,1381575.0,ISSUE,2003-07-23,2003-11-26,2003-11-26,Y,2004-04-26,2005-02-15,2003-12-22,2004-04-26,2008-03-31,NaN,41.943055,-87.682735,"{'latitude': '41.94305483117927', 'longitude':...",AAC,1,1,1,1,1,1
82726,1491427-20050106,1491427,9207,3,"UNCOMMON GROUND, INC.",UNCOMMON GROUND,3800 N CLARK ST,CHICAGO,IL,60613.0,44.0,50.0,44-50,19.0,1475,Consumption on Premises - Incidental Activity,1491427.0,ISSUE,2004-04-28,2004-09-01,2004-09-02,Y,2005-01-06,2005-08-15,2005-01-06,2005-01-06,2011-11-03,17.0,41.951064,-87.659795,"{'latitude': '41.951064053085005', 'longitude'...",AAC,1,1,1,1,1,1

In [61]:
df['APPLICATION TYPE'].value_counts()

RENEW     61085
ISSUE     23398
C_LOC      1400
C_CAPA        7
C_EXPA        5
Name: APPLICATION TYPE, dtype: int64

### getting dummies for "application type"

In [63]:
application_type=pd.get_dummies(df['APPLICATION TYPE'])

df=pd.concat([df,application_type],axis=1)

### now i will be handling the "legal name" as i did in the first notebook, all of it has been done in a single cell and dummies have been created

In [64]:

legal_list=[]
for x in df['LEGAL NAME']:
    legal_list.append(x.split(' ')[-1])
    
legal_list

df['LEGAL TYPE']=legal_list

df['LEGAL TYPE'].value_counts()[:20]

df['LEGAL TYPE'].replace('INC.','INC',inplace=True)
df['LEGAL TYPE'].replace('Inc.','INC',inplace=True)
df['LEGAL TYPE'].replace('Inc','INC',inplace=True)
df['LEGAL TYPE'].replace('INCORPORATED','INC',inplace=True)


df['LEGAL TYPE'].value_counts()[:20]

df['LEGAL TYPE'].replace('L.L.C.','LLC',inplace=True)
df['LEGAL TYPE'].replace('llc','LLC',inplace=True)
df['LEGAL TYPE'].replace('llc.','LLC',inplace=True)
df['LEGAL TYPE'].replace('LLC.','LLC',inplace=True)
df['LEGAL TYPE'].replace('L.L.C','LLC',inplace=True)




df['LEGAL TYPE'].value_counts()[:20]

df['LEGAL TYPE'].replace('corp','CORPORATION',inplace=True)
df['LEGAL TYPE'].replace('CORP','CORPORATION',inplace=True)
df['LEGAL TYPE'].replace('CORP.','CORPORATION',inplace=True)
df['LEGAL TYPE'].replace('corp.','CORPORATION',inplace=True)
df['LEGAL TYPE'].replace('corporation','CORPORATION',inplace=True)


df['LEGAL TYPE'].value_counts()[:20]

df['LEGAL TYPE'].replace('co','COMPANY',inplace=True)
df['LEGAL TYPE'].replace('CO.','COMPANY',inplace=True)
df['LEGAL TYPE'].replace('company','COMPANY',inplace=True)
df['LEGAL TYPE'].replace('CO','COMPANY',inplace=True)
df['LEGAL TYPE'].replace('co.','COMPANY',inplace=True)


df['LEGAL TYPE'].value_counts()[:20]

df['LEGAL TYPE'].replace('LTD.','LTD',inplace=True)
df['LEGAL TYPE'].replace('ltd.','LTD',inplace=True)
df['LEGAL TYPE'].replace('ltd','LTD',inplace=True)
df['LEGAL TYPE'].replace('limited','LTD',inplace=True)
df['LEGAL TYPE'].replace('limited.','LTD',inplace=True)
df['LEGAL TYPE'].replace('LIMITED','LTD',inplace=True)
df['LEGAL TYPE'].replace('LIMITED.','LTD',inplace=True)


df['LEGAL TYPE'].value_counts()[:20]

df['LEGAL TYPE'].replace('SERVICE','SERVICES',inplace=True)
df['LEGAL TYPE'].replace('service','SERVICES',inplace=True)
df['LEGAL TYPE'].replace('services','SERVICES',inplace=True)


df['LEGAL TYPE'].value_counts()[:20]

### so the top five value counts have significant numbers, thus it makes sense in encoding them, rest can reflect 0

legal_type_list=[]
for x in df['LEGAL TYPE']:
    if x not in ['INC','CORPORATION','LLC','COMPANY','LTD']:
        legal_type_list.append('OTHER')
    else:
        legal_type_list.append(x)
    

legal_type_list
len(legal_type_list)

df['LEGAL TYPE CLASSIFIED']=legal_type_list

df

### getting dummies from the "legal type classifed" column

legal_dummies=pd.get_dummies(df['LEGAL TYPE CLASSIFIED'],drop_first=True)

legal_dummies

df=pd.concat([df,legal_dummies],axis=1)

df.head()

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED,LICENSE STATUS CHANGE DATE ENCODED,C_CAPA,C_EXPA,C_LOC,ISSUE,RENEW,LEGAL TYPE,LEGAL TYPE CLASSIFIED,CORPORATION,INC,LLC,LTD,OTHER
0,35342-20020816,1256593,32811,1,CARMEN CAHUE,CLAUDIA'S BRIDAL SHOP,2625 S CENTRAL PARK AVE 1,CHICAGO,IL,60623.0,22.0,28.0,22-28,10.0,1010,Limited Business License,35342.0,RENEW,NaT,2002-06-28,2002-08-21,N,2002-08-16,2003-08-15,2002-08-21,2006-04-11,NaT,25.0,41.843613,-87.714618,"{'latitude': '41.843612879431845', 'longitude'...",AAI,0,1,1,1,1,0,0,0,0,0,1,CAHUE,OTHER,0,0,0,0,1
1,1358463-20051116,1639294,262311,29,"ISLA TROPICAL, INC.",ISLA TROPICAL,2825 W MONTROSE AVE,CHICAGO,IL,60618,33.0,23.0,33-23,17.0,1315,Mobile Food Dispenser,1358463.0,RENEW,NaT,2005-09-22,2005-11-03,N,2005-11-16,2006-11-15,2006-04-05,2006-06-12,2006-06-15,60.0,41.961132,-87.699626,"{'latitude': '41.96113244107215', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,INC,INC,0,1,0,0,0
2,1980233-20090722,1980233,345008,1,DJS REMODELING,"DJS REMODELING, INC.",1605 CLAVEY RD 1,HIGHLAND,IL,60035,NaN,NaN,NaN,NaN,1011,Home Repair,1980233.0,ISSUE,2009-06-29,2009-07-22,2009-07-22,N,2009-07-22,2011-07-15,2009-07-22,2009-07-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,REMODELING,OTHER,0,0,0,0,1
3,1476582-20040211,1476582,273121,1,ALL-BRY CONSTRUCTION CO.,ALL-BRY CONSTRUCTION CO.,8 NORTH TRAIL,LEMONT,IL,60439,NaN,NaN,NaN,NaN,1010,Limited Business License,1476582.0,ISSUE,2004-02-10,2004-02-10,2004-02-10,N,2004-02-11,2005-02-15,2004-02-10,2004-02-11,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,COMPANY,COMPANY,0,0,0,0,0
4,1141408-20080516,1896750,213785,1,MCDONOUGH MECHANICAL SERVICE,MCDONOUGH MECHANICAL SERVICE,4081 JOSEPH DR,WAUKEGAN,IL,60087,NaN,NaN,NaN,NaN,1010,Limited Business License,1141408.0,RENEW,NaT,2008-03-24,2008-06-04,N,2008-05-16,2010-05-15,2008-06-04,2008-06-05,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1,1,0,0,0,0,0,1,SERVICES,OTHER,0,0,0,0,1

### "site number" column is encoded and dummy is created

In [65]:
site_number_list=[]
for x in df['SITE NUMBER']:
    if x not in [1,2,3,4]:
        site_number_list.append('OTHER SITE')
    else:
        site_number_list.append(x)

site_number_list

df['SITE NUMBER ENCODED']=site_number_list

site_dummies=pd.get_dummies(df['SITE NUMBER ENCODED'],drop_first=True)
site_dummies

df=pd.concat([df,site_dummies],axis=1)

df.head()

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED,LICENSE STATUS CHANGE DATE ENCODED,C_CAPA,C_EXPA,C_LOC,ISSUE,RENEW,LEGAL TYPE,LEGAL TYPE CLASSIFIED,CORPORATION,INC,LLC,LTD,OTHER,SITE NUMBER ENCODED,2,3,4,OTHER SITE
0,35342-20020816,1256593,32811,1,CARMEN CAHUE,CLAUDIA'S BRIDAL SHOP,2625 S CENTRAL PARK AVE 1,CHICAGO,IL,60623.0,22.0,28.0,22-28,10.0,1010,Limited Business License,35342.0,RENEW,NaT,2002-06-28,2002-08-21,N,2002-08-16,2003-08-15,2002-08-21,2006-04-11,NaT,25.0,41.843613,-87.714618,"{'latitude': '41.843612879431845', 'longitude'...",AAI,0,1,1,1,1,0,0,0,0,0,1,CAHUE,OTHER,0,0,0,0,1,1,0,0,0,0
1,1358463-20051116,1639294,262311,29,"ISLA TROPICAL, INC.",ISLA TROPICAL,2825 W MONTROSE AVE,CHICAGO,IL,60618,33.0,23.0,33-23,17.0,1315,Mobile Food Dispenser,1358463.0,RENEW,NaT,2005-09-22,2005-11-03,N,2005-11-16,2006-11-15,2006-04-05,2006-06-12,2006-06-15,60.0,41.961132,-87.699626,"{'latitude': '41.96113244107215', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,INC,INC,0,1,0,0,0,OTHER SITE,0,0,0,1
2,1980233-20090722,1980233,345008,1,DJS REMODELING,"DJS REMODELING, INC.",1605 CLAVEY RD 1,HIGHLAND,IL,60035,NaN,NaN,NaN,NaN,1011,Home Repair,1980233.0,ISSUE,2009-06-29,2009-07-22,2009-07-22,N,2009-07-22,2011-07-15,2009-07-22,2009-07-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,REMODELING,OTHER,0,0,0,0,1,1,0,0,0,0
3,1476582-20040211,1476582,273121,1,ALL-BRY CONSTRUCTION CO.,ALL-BRY CONSTRUCTION CO.,8 NORTH TRAIL,LEMONT,IL,60439,NaN,NaN,NaN,NaN,1010,Limited Business License,1476582.0,ISSUE,2004-02-10,2004-02-10,2004-02-10,N,2004-02-11,2005-02-15,2004-02-10,2004-02-11,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,COMPANY,COMPANY,0,0,0,0,0,1,0,0,0,0
4,1141408-20080516,1896750,213785,1,MCDONOUGH MECHANICAL SERVICE,MCDONOUGH MECHANICAL SERVICE,4081 JOSEPH DR,WAUKEGAN,IL,60087,NaN,NaN,NaN,NaN,1010,Limited Business License,1141408.0,RENEW,NaT,2008-03-24,2008-06-04,N,2008-05-16,2010-05-15,2008-06-04,2008-06-05,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1,1,0,0,0,0,0,1,SERVICES,OTHER,0,0,0,0,1,1,0,0,0,0

### i will now be encoding the "license code" column

In [66]:

license_code_list=[]
for x in df['LICENSE CODE']:
    if x not in [1010,1011,1012,1006,1525,1676,1008,1020]:
        license_code_list.append('OTHER LICENSE CODE')
    else:
        license_code_list.append(x)

df['LICENSE CODE ENCODED']=license_code_list
df

license_code_dummy=pd.get_dummies(df['LICENSE CODE ENCODED'],drop_first=True)

df=pd.concat([df,license_code_dummy],axis=1)
df

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED,LICENSE STATUS CHANGE DATE ENCODED,C_CAPA,C_EXPA,C_LOC,ISSUE,RENEW,LEGAL TYPE,LEGAL TYPE CLASSIFIED,CORPORATION,INC,LLC,LTD,OTHER,SITE NUMBER ENCODED,2,3,4,OTHER SITE,LICENSE CODE ENCODED,1008,1010,1011,1012,1020,1525,1676,OTHER LICENSE CODE
0,35342-20020816,1256593,32811,1,CARMEN CAHUE,CLAUDIA'S BRIDAL SHOP,2625 S CENTRAL PARK AVE 1,CHICAGO,IL,60623.0,22.0,28.0,22-28,10.0,1010,Limited Business License,35342.0,RENEW,NaT,2002-06-28,2002-08-21,N,2002-08-16,2003-08-15,2002-08-21,2006-04-11,NaT,25.0,41.843613,-87.714618,"{'latitude': '41.843612879431845', 'longitude'...",AAI,0,1,1,1,1,0,0,0,0,0,1,CAHUE,OTHER,0,0,0,0,1,1,0,0,0,0,1010,0,1,0,0,0,0,0,0
1,1358463-20051116,1639294,262311,29,"ISLA TROPICAL, INC.",ISLA TROPICAL,2825 W MONTROSE AVE,CHICAGO,IL,60618,33.0,23.0,33-23,17.0,1315,Mobile Food Dispenser,1358463.0,RENEW,NaT,2005-09-22,2005-11-03,N,2005-11-16,2006-11-15,2006-04-05,2006-06-12,2006-06-15,60.0,41.961132,-87.699626,"{'latitude': '41.96113244107215', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,INC,INC,0,1,0,0,0,OTHER SITE,0,0,0,1,OTHER LICENSE CODE,0,0,0,0,0,0,0,1
2,1980233-20090722,1980233,345008,1,DJS REMODELING,"DJS REMODELING, INC.",1605 CLAVEY RD 1,HIGHLAND,IL,60035,NaN,NaN,NaN,NaN,1011,Home Repair,1980233.0,ISSUE,2009-06-29,2009-07-22,2009-07-22,N,2009-07-22,2011-07-15,2009-07-22,2009-07-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,REMODELING,OTHER,0,0,0,0,1,1,0,0,0,0,1011,0,0,1,0,0,0,0,0
3,1476582-20040211,1476582,273121,1,ALL-BRY CONSTRUCTION CO.,ALL-BRY CONSTRUCTION CO.,8 NORTH TRAIL,LEMONT,IL,60439,NaN,NaN,NaN,NaN,1010,Limited Business License,1476582.0,ISSUE,2004-02-10,2004-02-10,2004-02-10,N,2004-02-11,2005-02-15,2004-02-10,2004-02-11,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,COMPANY,COMPANY,0,0,0,0,0,1,0,0,0,0,1010,0,1,0,0,0,0,0,0
4,1141408-20080516,1896750,213785,1,MCDONOUGH MECHANICAL SERVICE,MCDONOUGH MECHANICAL SERVICE,4081 JOSEPH DR,WAUKEGAN,IL,60087,NaN,NaN,NaN,NaN,1010,Limited Business License,1141408.0,RENEW,NaT,2008-03-24,2008-06-04,N,2008-05-16,2010-05-15,2008-06-04,2008-06-05,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1,1,0,0,0,0,0,1,SERVICES,OTHER,0,0,0,0,1,1,0,0,0,0,1010,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85890,12652-20120516,2143400,8011,1,UNITED PARCEL SERVICE,UNITED PARCEL SERVICE,1400 S JEFFERSON ST,CHICAGO,IL,60607.0,11.0,28.0,11-28,1.0,1008,Hazardous Materials,12652.0,RENEW,NaT,2012-03-15,2012-05-07,N,2012-05-16,2014-05-15,2012-05-07,2012-05-08,2012-12-29,NaN,41.863501,-87.642210,"{'latitude': '41.86350135244771', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,SERVICES,OTHER,0,0,0,0,1,1,0,0,0,0,1008,1,0,0,0,0,0,0,0
85891,1821421-20070522,1821421,317725,1,"EXPRESS BOARD UP SERVICE, INC.","EXPRESS BOARD UP SERVICE, INC.",8707 VANGUARD DR,MACHESNEY PARK,IL,61115.0,NaN,NaN,NaN,NaN,1800,Board-Up Work,1821421.0,ISSUE,2007-05-21,2007-05-22,2007-05-22,N,2007-05-22,2009-06-15,2007-05-22,2007-05-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,INC,INC,0,1,0,0,0,1,0,0,0,0,OTHER LICENSE CODE,0,0,0,0,0,0,0,1
85892,74137-20090116,1939358,8458,2,ARAMARK SMMS LLC,ARAMARK FACILITY SERVICES,2300 WARRENVILLE RD 1ST,DOWNERS GROVE,IL,60515.0,NaN,NaN,NaN,NaN,1010,Limited Business License,74137.0,RENEW,NaT,2008-11-14,2009-01-09,N,2009-01-16,2011-01-15,2009-01-09,2009-12-08,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1,1,0,0,0,0,0,1,LLC,LLC,0,0,1,0,0,2,1,0,0,0,1010,0,1,0,0,0,0,0,0
85893,2049545-20111016,2110060,2156,43,GENERAL NUTRITION CORPORATION,GENERAL NUTRITION CENTER # 61,5151 S PULASKI RD SLAB ON GRADE T-21,CHICAGO,IL,60632.0,23.0,NaN,23-,NaN,1010,Limited Business License,2049545.0,RENEW,NaT,2011-08-15,2011-10-03,N,2011-10-16,2013-10-15,2011-10-03,2011-10-11,2012-05-08,NaN,41.799012,-87.723181,"{'latitude': '41.79901235310339', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,CORPORATION,CORPORATION,1,0,0,0,0,OTHER SITE,0,0,0,1,1010,0,1,0,0,0,0,0,0
85894,1070196-20040216,1461628,205936,1,JUAN CARLOS ERAZO,CASA DE JUAN RESTAURANT,5814 W FULLERTON AVE,CHICAGO,IL,60639.0,30.0,52.0,30-52,25.0,1006,Retail Food Establishment,1070196.0,RENEW,NaT,2003-12-15,2004-02-06,N,2004-02-16,2005-02-15,2003-12-22,2004-02-09,2005-01-07,NaN,41.924004,-87.771507,"{'latitude': '41.92400390449922', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,ERAZO,OTHER,0,0,0,0,1,1,0,0,0,0,1006,0,0,0,0,0,0,0,0

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85895 entries, 0 to 85894
Data columns (total 64 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   ID                                     85895 non-null  object
 1   LICENSE ID                             85895 non-null  int64
 2   ACCOUNT NUMBER                         85895 non-null  int64
 3   SITE NUMBER                            85895 non-null  int64
 4   LEGAL NAME                             85895 non-null  object
 5   DOING BUSINESS AS NAME                 85894 non-null  object
 6   ADDRESS                                85895 non-null  object
 7   CITY                                   85895 non-null  object
 8   STATE                                  85895 non-null  object
 9   ZIP CODE                               85864 non-null  object
 10  WARD                                   36194 non-null  float64
 11  PRECINCT                               29194 non-null  float64
 12  WARD PRECINCT                          36195 non-null  object
 13  POLICE DISTRICT                        31883 non-null  float64
 14  LICENSE CODE                           85895 non-null  int64
 15  LICENSE DESCRIPTION                    85895 non-null  object
 16  LICENSE NUMBER                         85894 non-null  float64
 17  APPLICATION TYPE                       85895 non-null  object
 18  APPLICATION CREATED DATE               21235 non-null  datetime64[ns]
 19  APPLICATION REQUIREMENTS COMPLETE      85681 non-null  datetime64[ns]
 20  PAYMENT DATE                           84606 non-null  datetime64[ns]
 21  CONDITIONAL APPROVAL                   85895 non-null  object
 22  LICENSE TERM START DATE                85667 non-null  datetime64[ns]
 23  LICENSE TERM EXPIRATION DATE           85877 non-null  datetime64[ns]
 24  LICENSE APPROVED FOR ISSUANCE          79106 non-null  datetime64[ns]
 25  DATE ISSUED                            85895 non-null  datetime64[ns]
 26  LICENSE STATUS CHANGE DATE             30495 non-null  datetime64[ns]
 27  SSA                                    9449 non-null   float64
 28  LATITUDE                               38649 non-null  float64
 29  LONGITUDE                              38649 non-null  float64
 30  LOCATION                               38649 non-null  object
 31  LICENSE STATUS                         85895 non-null  object
 32  APPLICATION CREATE DATE ENCODED        85895 non-null  int64
 33  APPLICATION REQUEST COMPLETE ENCODED   85895 non-null  int64
 34  PAYMENT DATE ENCODED                   85895 non-null  int64
 35  LICENSE TERM START DATE ENCODED        85895 non-null  int64
 36  LICENSE APPROVED FOR ISSUANCE ENCODED  85895 non-null  int64
 37  LICENSE STATUS CHANGE DATE ENCODED     85895 non-null  int64
 38  C_CAPA                                 85895 non-null  uint8
 39  C_EXPA                                 85895 non-null  uint8
 40  C_LOC                                  85895 non-null  uint8
 41  ISSUE                                  85895 non-null  uint8
 42  RENEW                                  85895 non-null  uint8
 43  LEGAL TYPE                             85895 non-null  object
 44  LEGAL TYPE CLASSIFIED                  85895 non-null  object
 45  CORPORATION                            85895 non-null  uint8
 46  INC                                    85895 non-null  uint8
 47  LLC                                    85895 non-null  uint8
 48  LTD                                    85895 non-null  uint8
 49  OTHER                                  85895 non-null  uint8
 50  SITE NUMBER ENCODED                    85895 non-null  object
 51  2                                      85895 non-null  uint8
 52  3                                      85895 non-null  uint8
 53  4                                      85895 non-null  uint8
 54  OTHER SITE                             85895 non-null  uint8
 55  LICENSE CODE ENCODED                   85895 non-null  object
 56  1008                                   85895 non-null  uint8
 57  1010                                   85895 non-null  uint8
 58  1011                                   85895 non-null  uint8
 59  1012                                   85895 non-null  uint8
 60  1020                                   85895 non-null  uint8
 61  1525                                   85895 non-null  uint8
 62  1676                                   85895 non-null  uint8
 63  OTHER LICENSE CODE                     85895 non-null  uint8
dtypes: datetime64[ns](8), float64(7), int64(10), object(17), uint8(22)
memory usage: 29.3+ MB

### encoding license description

In [68]:

license_description_list=[]
for x in df['LICENSE DESCRIPTION']:
    if x not in ['Limited Business License','Home Repair','Home Occupation','Retail Food Establishment','Massage Therapist','Scavenger, Private','Hazardous Materials','Residential Real Estate Developer']:
        license_description_list.append('OTHER LICENSE DESC')
    else:
        license_description_list.append(x)

license_description_list

df['LICENSE DESCRIPTION ENCODED']=license_description_list
df

license_description_dummy=pd.get_dummies(df['LICENSE DESCRIPTION ENCODED'])

df=pd.concat([df,license_description_dummy],axis=1)

df

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED,LICENSE STATUS CHANGE DATE ENCODED,C_CAPA,C_EXPA,C_LOC,ISSUE,RENEW,LEGAL TYPE,LEGAL TYPE CLASSIFIED,CORPORATION,INC,LLC,LTD,OTHER,SITE NUMBER ENCODED,2,3,4,OTHER SITE,LICENSE CODE ENCODED,1008,1010,1011,1012,1020,1525,1676,OTHER LICENSE CODE,LICENSE DESCRIPTION ENCODED,Hazardous Materials,Home Occupation,Home Repair,Limited Business License,Massage Therapist,OTHER LICENSE DESC,Residential Real Estate Developer,Retail Food Establishment,"Scavenger, Private"
0,35342-20020816,1256593,32811,1,CARMEN CAHUE,CLAUDIA'S BRIDAL SHOP,2625 S CENTRAL PARK AVE 1,CHICAGO,IL,60623.0,22.0,28.0,22-28,10.0,1010,Limited Business License,35342.0,RENEW,NaT,2002-06-28,2002-08-21,N,2002-08-16,2003-08-15,2002-08-21,2006-04-11,NaT,25.0,41.843613,-87.714618,"{'latitude': '41.843612879431845', 'longitude'...",AAI,0,1,1,1,1,0,0,0,0,0,1,CAHUE,OTHER,0,0,0,0,1,1,0,0,0,0,1010,0,1,0,0,0,0,0,0,Limited Business License,0,0,0,1,0,0,0,0,0
1,1358463-20051116,1639294,262311,29,"ISLA TROPICAL, INC.",ISLA TROPICAL,2825 W MONTROSE AVE,CHICAGO,IL,60618,33.0,23.0,33-23,17.0,1315,Mobile Food Dispenser,1358463.0,RENEW,NaT,2005-09-22,2005-11-03,N,2005-11-16,2006-11-15,2006-04-05,2006-06-12,2006-06-15,60.0,41.961132,-87.699626,"{'latitude': '41.96113244107215', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,INC,INC,0,1,0,0,0,OTHER SITE,0,0,0,1,OTHER LICENSE CODE,0,0,0,0,0,0,0,1,OTHER LICENSE DESC,0,0,0,0,0,1,0,0,0
2,1980233-20090722,1980233,345008,1,DJS REMODELING,"DJS REMODELING, INC.",1605 CLAVEY RD 1,HIGHLAND,IL,60035,NaN,NaN,NaN,NaN,1011,Home Repair,1980233.0,ISSUE,2009-06-29,2009-07-22,2009-07-22,N,2009-07-22,2011-07-15,2009-07-22,2009-07-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,REMODELING,OTHER,0,0,0,0,1,1,0,0,0,0,1011,0,0,1,0,0,0,0,0,Home Repair,0,0,1,0,0,0,0,0,0
3,1476582-20040211,1476582,273121,1,ALL-BRY CONSTRUCTION CO.,ALL-BRY CONSTRUCTION CO.,8 NORTH TRAIL,LEMONT,IL,60439,NaN,NaN,NaN,NaN,1010,Limited Business License,1476582.0,ISSUE,2004-02-10,2004-02-10,2004-02-10,N,2004-02-11,2005-02-15,2004-02-10,2004-02-11,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,COMPANY,COMPANY,0,0,0,0,0,1,0,0,0,0,1010,0,1,0,0,0,0,0,0,Limited Business License,0,0,0,1,0,0,0,0,0
4,1141408-20080516,1896750,213785,1,MCDONOUGH MECHANICAL SERVICE,MCDONOUGH MECHANICAL SERVICE,4081 JOSEPH DR,WAUKEGAN,IL,60087,NaN,NaN,NaN,NaN,1010,Limited Business License,1141408.0,RENEW,NaT,2008-03-24,2008-06-04,N,2008-05-16,2010-05-15,2008-06-04,2008-06-05,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1,1,0,0,0,0,0,1,SERVICES,OTHER,0,0,0,0,1,1,0,0,0,0,1010,0,1,0,0,0,0,0,0,Limited Business License,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85890,12652-20120516,2143400,8011,1,UNITED PARCEL SERVICE,UNITED PARCEL SERVICE,1400 S JEFFERSON ST,CHICAGO,IL,60607.0,11.0,28.0,11-28,1.0,1008,Hazardous Materials,12652.0,RENEW,NaT,2012-03-15,2012-05-07,N,2012-05-16,2014-05-15,2012-05-07,2012-05-08,2012-12-29,NaN,41.863501,-87.642210,"{'latitude': '41.86350135244771', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,SERVICES,OTHER,0,0,0,0,1,1,0,0,0,0,1008,1,0,0,0,0,0,0,0,Hazardous Materials,1,0,0,0,0,0,0,0,0
85891,1821421-20070522,1821421,317725,1,"EXPRESS BOARD UP SERVICE, INC.","EXPRESS BOARD UP SERVICE, INC.",8707 VANGUARD DR,MACHESNEY PARK,IL,61115.0,NaN,NaN,NaN,NaN,1800,Board-Up Work,1821421.0,ISSUE,2007-05-21,2007-05-22,2007-05-22,N,2007-05-22,2009-06-15,2007-05-22,2007-05-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,INC,INC,0,1,0,0,0,1,0,0,0,0,OTHER LICENSE CODE,0,0,0,0,0,0,0,1,OTHER LICENSE DESC,0,0,0,0,0,1,0,0,0
85892,74137-20090116,1939358,8458,2,ARAMARK SMMS LLC,ARAMARK FACILITY SERVICES,2300 WARRENVILLE RD 1ST,DOWNERS GROVE,IL,60515.0,NaN,NaN,NaN,NaN,1010,Limited Business License,74137.0,RENEW,NaT,2008-11-14,2009-01-09,N,2009-01-16,2011-01-15,2009-01-09,2009-12-08,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1,1,0,0,0,0,0,1,LLC,LLC,0,0,1,0,0,2,1,0,0,0,1010,0,1,0,0,0,0,0,0,Limited Business License,0,0,0,1,0,0,0,0,0
85893,2049545-20111016,2110060,2156,43,GENERAL NUTRITION CORPORATION,GENERAL NUTRITION CENTER # 61,5151 S PULASKI RD SLAB ON GRADE T-21,CHICAGO,IL,60632.0,23.0,NaN,23-,NaN,1010,Limited Business License,2049545.0,RENEW,NaT,2011-08-15,2011-10-03,N,2011-10-16,2013-10-15,2011-10-03,2011-10-11,2012-05-08,NaN,41.799012,-87.723181,"{'latitude': '41.79901235310339', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,CORPORATION,CORPORATION,1,0,0,0,0,OTHER SITE,0,0,0,1,1010,0,1,0,0,0,0,0,0,Limited Business License,0,0,0,1,0,0,0,0,0
85894,1070196-20040216,1461628,205936,1,JUAN CARLOS ERAZO,CASA DE JUAN RESTAURANT,5814 W FULLERTON AVE,CHICAGO,IL,60639.0,30.0,52.0,30-52,25.0,1006,Retail Food Establishment,1070196.0,RENEW,NaT,2003-12-15,2004-02-06,N,2004-02-16,2005-02-15,2003-12-22,2004-02-09,2005-01-07,NaN,41.924004,-87.771507,"{'latitude': '41.92400390449922', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,ERAZO,OTHER,0,0,0,0,1,1,0,0,0,0,1006,0,0,0,0,0,0,0,0,Retail Food Establishment,0,0,0,0,0,0,0,1,0

In [69]:
df.columns

Index([                                   'ID',
                                  'LICENSE ID',
                              'ACCOUNT NUMBER',
                                 'SITE NUMBER',
                                  'LEGAL NAME',
                      'DOING BUSINESS AS NAME',
                                     'ADDRESS',
                                        'CITY',
                                       'STATE',
                                    'ZIP CODE',
                                        'WARD',
                                    'PRECINCT',
                               'WARD PRECINCT',
                             'POLICE DISTRICT',
                                'LICENSE CODE',
                         'LICENSE DESCRIPTION',
                              'LICENSE NUMBER',
                            'APPLICATION TYPE',
                    'APPLICATION CREATED DATE',
           'APPLICATION REQUIREMENTS COMPLETE',
                                'PAYMENT DATE',
                        'CONDITIONAL APPROVAL',
                     'LICENSE TERM START DATE',
                'LICENSE TERM EXPIRATION DATE',
               'LICENSE APPROVED FOR ISSUANCE',
                                 'DATE ISSUED',
                  'LICENSE STATUS CHANGE DATE',
                                         'SSA',
                                    'LATITUDE',
                                   'LONGITUDE',
                                    'LOCATION',
                              'LICENSE STATUS',
             'APPLICATION CREATE DATE ENCODED',
        'APPLICATION REQUEST COMPLETE ENCODED',
                        'PAYMENT DATE ENCODED',
             'LICENSE TERM START DATE ENCODED',
       'LICENSE APPROVED FOR ISSUANCE ENCODED',
          'LICENSE STATUS CHANGE DATE ENCODED',
                                      'C_CAPA',
                                      'C_EXPA',
                                       'C_LOC',
                                       'ISSUE',
                                       'RENEW',
                                  'LEGAL TYPE',
                       'LEGAL TYPE CLASSIFIED',
                                 'CORPORATION',
                                         'INC',
                                         'LLC',
                                         'LTD',
                                       'OTHER',
                         'SITE NUMBER ENCODED',
                                             2,
                                             3,
                                             4,
                                  'OTHER SITE',
                        'LICENSE CODE ENCODED',
                                          1008,
                                          1010,
                                          1011,
                                          1012,
                                          1020,
                                          1525,
                                          1676,
                          'OTHER LICENSE CODE',
                 'LICENSE DESCRIPTION ENCODED',
                         'Hazardous Materials',
                             'Home Occupation',
                                 'Home Repair',
                    'Limited Business License',
                           'Massage Therapist',
                          'OTHER LICENSE DESC',
           'Residential Real Estate Developer',
                   'Retail Food Establishment',
                          'Scavenger, Private'],
      dtype='object')

### now i will split the data and train several models

In [73]:
X=df[['APPLICATION CREATE DATE ENCODED',
        'APPLICATION REQUEST COMPLETE ENCODED',
                        'PAYMENT DATE ENCODED',
             'LICENSE TERM START DATE ENCODED',
       'LICENSE APPROVED FOR ISSUANCE ENCODED',
          'LICENSE STATUS CHANGE DATE ENCODED',
                                      'C_CAPA',
                                      'C_EXPA',
                                       'C_LOC',
                                       'ISSUE',
                                       'RENEW',
                                 
                                 'CORPORATION',
                                         'INC',
                                         'LLC',
                                         'LTD',
                                       'OTHER',
                                             2,
                                             3,
                                             4,
                                  'OTHER SITE',
                                          1008,
                                          1010,
                                          1011,
                                          1012,
                                          1020,
                                          1525,
                                          1676,
                          'OTHER LICENSE CODE',
                         'Hazardous Materials',
                             'Home Occupation',
                                 'Home Repair',
                    'Limited Business License',
                           'Massage Therapist',
                          'OTHER LICENSE DESC',
           'Residential Real Estate Developer',
                   'Retail Food Establishment',
                          'Scavenger, Private']]

In [75]:
X.isnull().sum()

APPLICATION CREATE DATE ENCODED          0
APPLICATION REQUEST COMPLETE ENCODED     0
PAYMENT DATE ENCODED                     0
LICENSE TERM START DATE ENCODED          0
LICENSE APPROVED FOR ISSUANCE ENCODED    0
LICENSE STATUS CHANGE DATE ENCODED       0
C_CAPA                                   0
C_EXPA                                   0
C_LOC                                    0
ISSUE                                    0
RENEW                                    0
CORPORATION                              0
INC                                      0
LLC                                      0
LTD                                      0
OTHER                                    0
2                                        0
3                                        0
4                                        0
OTHER SITE                               0
1008                                     0
1010                                     0
1011                                     0
1012                                     0
1020                                     0
1525                                     0
1676                                     0
OTHER LICENSE CODE                       0
Hazardous Materials                      0
Home Occupation                          0
Home Repair                              0
Limited Business License                 0
Massage Therapist                        0
OTHER LICENSE DESC                       0
Residential Real Estate Developer        0
Retail Food Establishment                0
Scavenger, Private                       0
dtype: int64

In [91]:
replacement_dict={'AAI':1,'AAC':2,'REV':3,'REA':4,'INQ':5}
df['LICENSE STATUS'].replace(replacement_dict,inplace=True)

In [92]:
y=df['LICENSE STATUS']

In [80]:
X=X.values

In [93]:
y=y.values

In [138]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33)

from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier(n_estimators=1000)

rfc.fit(X_train,y_train)

y_hat=rfc.predict(X_test)

from sklearn.metrics import accuracy_score

random_forest_acc=accuracy_score(y_test,y_hat)

In [95]:
from sklearn.metrics import confusion_matrix

In [103]:
confusion_matrix(y_test,y_hat)

array([[18203,     0,     0,     0],
       [    0, 10049,     1,     0],
       [    0,    91,     1,     0],
       [    0,     1,     0,     0]])

In [137]:
from sklearn.linear_model import LogisticRegression

lr=LogisticRegression()

lr.fit(X_train,y_train)

logistic_regression_acc=accuracy_score(lr.predict(X_test),y_test)

/Users/prakritsinha/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [139]:
from sklearn.svm import SVC

svc=SVC()

svc.fit(X_train,y_train)

y_hat_svc=svc.predict(X_test)

support_vector_classifier_acc=accuracy_score(y_test,y_hat)

### a breif summary of models:

In [142]:
print(f'Random forest regressor accuracy: {random_forest_acc}')
print(f'support vector machine accuracy: {support_vector_classifier_acc}')
print(f'logistic regression accuracy: {logistic_regression_acc}')

Random forest regressor accuracy: 0.996824948846398
support vector machine accuracy: 0.996824948846398
logistic regression accuracy: 0.9967191138079446

### now ill prepare the test data so it can be fed to the model

In [104]:
test=pd.read_csv('test_file.csv',parse_dates=['APPLICATION CREATED DATE', 'APPLICATION REQUIREMENTS COMPLETE',
       'PAYMENT DATE','LICENSE TERM START DATE',
       'LICENSE TERM EXPIRATION DATE', 'LICENSE APPROVED FOR ISSUANCE',
       'DATE ISSUED', 'LICENSE STATUS CHANGE DATE'])
test

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION
0,1516615-20120216,2132209,280120,1,RS HOMES I LLC,RS HOMES I LLC,350 W HUBBARD ST 3 300,CHICAGO,IL,60610.0,42.0,67.0,42-67,18.0,1020,Residential Real Estate Developer,1516615.0,RENEW,NaT,2011-12-15,2012-01-19,N,2012-02-16,2014-02-15,2012-01-19,2012-01-20,2012-12-29,NaN,41.890047,-87.637467,"{'latitude': '41.89004724888915', 'longitude':..."
1,69813-20110616,2090759,65043,1,CSX INTERMODAL INC,CSX INTERMODAL,2101 W 59TH ST 1ST,CHICAGO,IL,60636.0,16.0,5.0,16-5,7.0,1010,Limited Business License,69813.0,RENEW,NaT,2011-04-15,2012-11-02,N,2011-06-16,2013-06-15,2012-11-02,2012-11-05,2012-12-29,NaN,41.786485,-87.676665,"{'latitude': '41.786485235679486', 'longitude'..."
2,1519227-20041116,1541990,281270,1,LOCOMIBILE LOFTS LLC,LOCOMOBILE LOFTS LLC,1133 S WABASH AVE 1ST,CHICAGO,IL,60605.0,4.0,8.0,4-8,1.0,1020,Residential Real Estate Developer,1519227.0,RENEW,NaT,2004-09-27,2004-12-06,N,2004-11-16,2005-11-15,2004-12-06,2004-12-07,NaT,NaN,41.868269,-87.625695,"{'latitude': '41.86826924843568', 'longitude':..."
3,1922025-20100816,2041053,335243,1,ANNA F. JAMISON,ANNA F. JAMISON,13156 S FORRESTVILLE AVE,CHICAGO,IL,60827.0,9.0,33.0,9-33,5.0,1607,"Peddler, non-food, special",1922025.0,RENEW,NaT,2010-06-15,2010-11-04,N,2010-08-16,2012-08-15,NaT,2010-11-04,2012-12-31,NaN,41.655762,-87.608686,"{'latitude': '41.65576175146191', 'longitude':..."
4,1675683-20070816,1837158,283018,3,MARINCA A. COVARRUBIAS,DETAILS,4208 S ARCHER AVE,CHICAGO,IL,60632.0,15.0,26.0,15-26,9.0,1010,Limited Business License,1675683.0,RENEW,NaT,2007-06-21,2007-08-15,N,2007-08-16,2009-06-15,2007-08-15,2007-08-16,2008-03-26,39.0,41.816969,-87.699785,"{'latitude': '41.81696910012824', 'longitude':..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57234,1743194-20070816,1835677,266103,3,"GOODHEALTH MEDICAL PRODUCTS, INC.","GOODHEALTH MEDICAL PRODUCTS, INC.",2621 W 79TH ST,CHICAGO,IL,60652.0,18.0,14.0,18-14,8.0,1010,Limited Business License,1743194.0,RENEW,NaT,2007-06-21,2007-09-12,N,2007-08-16,2009-11-15,2007-09-12,2007-09-18,2008-03-17,NaN,41.749842,-87.688733,"{'latitude': '41.74984206916219', 'longitude':..."
57235,2032383-20160716,2465962,63376,180,INTERPARK LLC,INTERPARK,505 N STATE ST 2-4,CHICAGO,IL,60654.0,42.0,22.0,42-22,18.0,1002,Accessory Garage,2032383.0,RENEW,NaT,2016-05-15,2016-06-23,N,2016-07-16,2018-07-15,2016-06-23,2016-08-11,2018-01-09,NaN,41.891055,-87.627898,"{'latitude': '41.89105524147196', 'longitude':..."
57236,40376-20020216,1211199,55051,1,YUN HEE HWANG,TOP CLEANERS,1201 W ROSCOE ST 1ST,CHICAGO,IL,60657.0,44.0,9.0,44-9,19.0,1010,Limited Business License,40376.0,RENEW,NaT,2001-12-20,2002-01-18,N,2002-02-16,2003-02-15,2002-01-18,2002-01-22,NaT,NaN,41.943382,-87.659191,"{'latitude': '41.94338183750669', 'longitude':..."
57237,2064176-20121116,2188497,357381,1,D. C. A. TOWING INCORPORATED,D. C. A. TOWING INCORPORATED,7052 W 64TH ST 1ST,CHICAGO,IL,60638.0,23.0,18.0,23-18,8.0,1012,Home Occupation,2064176.0,RENEW,NaT,2012-09-14,2012-12-25,N,2012-11-16,2014-11-15,2012-12-25,2012-12-26,2012-12-29,NaN,41.775710,-87.798009,"{'latitude': '41.775709631013335', 'longitude'..."
57238,1954052-20090202,1954052,340610,1,maria t bedoy,mari's cleaning services,4544 S CHRISTIANA AVE 1,CHICAGO,IL,60632.0,14.0,10.0,14-10,8.0,1012,Home Occupation,1954052.0,ISSUE,NaT,2009-01-31,2009-01-31,N,2009-02-02,2009-06-15,2009-01-31,2009-02-02,NaT,39.0,41.810523,-87.707872,"{'latitude': '41.81052250782054', 'longitude':..."

In [105]:
appl_creat_date=[]
for x in test['APPLICATION CREATED DATE']:
    if type(x)==pd._libs.tslibs.nattype.NaTType:
        appl_creat_date.append(0)
    else:    
        appl_creat_date.append(1)
test['APPLICATION CREATE DATE ENCODED']=appl_creat_date

In [106]:
test

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,APPLICATION CREATE DATE ENCODED
0,1516615-20120216,2132209,280120,1,RS HOMES I LLC,RS HOMES I LLC,350 W HUBBARD ST 3 300,CHICAGO,IL,60610.0,42.0,67.0,42-67,18.0,1020,Residential Real Estate Developer,1516615.0,RENEW,NaT,2011-12-15,2012-01-19,N,2012-02-16,2014-02-15,2012-01-19,2012-01-20,2012-12-29,NaN,41.890047,-87.637467,"{'latitude': '41.89004724888915', 'longitude':...",0
1,69813-20110616,2090759,65043,1,CSX INTERMODAL INC,CSX INTERMODAL,2101 W 59TH ST 1ST,CHICAGO,IL,60636.0,16.0,5.0,16-5,7.0,1010,Limited Business License,69813.0,RENEW,NaT,2011-04-15,2012-11-02,N,2011-06-16,2013-06-15,2012-11-02,2012-11-05,2012-12-29,NaN,41.786485,-87.676665,"{'latitude': '41.786485235679486', 'longitude'...",0
2,1519227-20041116,1541990,281270,1,LOCOMIBILE LOFTS LLC,LOCOMOBILE LOFTS LLC,1133 S WABASH AVE 1ST,CHICAGO,IL,60605.0,4.0,8.0,4-8,1.0,1020,Residential Real Estate Developer,1519227.0,RENEW,NaT,2004-09-27,2004-12-06,N,2004-11-16,2005-11-15,2004-12-06,2004-12-07,NaT,NaN,41.868269,-87.625695,"{'latitude': '41.86826924843568', 'longitude':...",0
3,1922025-20100816,2041053,335243,1,ANNA F. JAMISON,ANNA F. JAMISON,13156 S FORRESTVILLE AVE,CHICAGO,IL,60827.0,9.0,33.0,9-33,5.0,1607,"Peddler, non-food, special",1922025.0,RENEW,NaT,2010-06-15,2010-11-04,N,2010-08-16,2012-08-15,NaT,2010-11-04,2012-12-31,NaN,41.655762,-87.608686,"{'latitude': '41.65576175146191', 'longitude':...",0
4,1675683-20070816,1837158,283018,3,MARINCA A. COVARRUBIAS,DETAILS,4208 S ARCHER AVE,CHICAGO,IL,60632.0,15.0,26.0,15-26,9.0,1010,Limited Business License,1675683.0,RENEW,NaT,2007-06-21,2007-08-15,N,2007-08-16,2009-06-15,2007-08-15,2007-08-16,2008-03-26,39.0,41.816969,-87.699785,"{'latitude': '41.81696910012824', 'longitude':...",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57234,1743194-20070816,1835677,266103,3,"GOODHEALTH MEDICAL PRODUCTS, INC.","GOODHEALTH MEDICAL PRODUCTS, INC.",2621 W 79TH ST,CHICAGO,IL,60652.0,18.0,14.0,18-14,8.0,1010,Limited Business License,1743194.0,RENEW,NaT,2007-06-21,2007-09-12,N,2007-08-16,2009-11-15,2007-09-12,2007-09-18,2008-03-17,NaN,41.749842,-87.688733,"{'latitude': '41.74984206916219', 'longitude':...",0
57235,2032383-20160716,2465962,63376,180,INTERPARK LLC,INTERPARK,505 N STATE ST 2-4,CHICAGO,IL,60654.0,42.0,22.0,42-22,18.0,1002,Accessory Garage,2032383.0,RENEW,NaT,2016-05-15,2016-06-23,N,2016-07-16,2018-07-15,2016-06-23,2016-08-11,2018-01-09,NaN,41.891055,-87.627898,"{'latitude': '41.89105524147196', 'longitude':...",0
57236,40376-20020216,1211199,55051,1,YUN HEE HWANG,TOP CLEANERS,1201 W ROSCOE ST 1ST,CHICAGO,IL,60657.0,44.0,9.0,44-9,19.0,1010,Limited Business License,40376.0,RENEW,NaT,2001-12-20,2002-01-18,N,2002-02-16,2003-02-15,2002-01-18,2002-01-22,NaT,NaN,41.943382,-87.659191,"{'latitude': '41.94338183750669', 'longitude':...",0
57237,2064176-20121116,2188497,357381,1,D. C. A. TOWING INCORPORATED,D. C. A. TOWING INCORPORATED,7052 W 64TH ST 1ST,CHICAGO,IL,60638.0,23.0,18.0,23-18,8.0,1012,Home Occupation,2064176.0,RENEW,NaT,2012-09-14,2012-12-25,N,2012-11-16,2014-11-15,2012-12-25,2012-12-26,2012-12-29,NaN,41.775710,-87.798009,"{'latitude': '41.775709631013335', 'longitude'...",0
57238,1954052-20090202,1954052,340610,1,maria t bedoy,mari's cleaning services,4544 S CHRISTIANA AVE 1,CHICAGO,IL,60632.0,14.0,10.0,14-10,8.0,1012,Home Occupation,1954052.0,ISSUE,NaT,2009-01-31,2009-01-31,N,2009-02-02,2009-06-15,2009-01-31,2009-02-02,NaT,39.0,41.810523,-87.707872,"{'latitude': '41.81052250782054', 'longitude':...",0

In [107]:
appl_req_complete=[]
for x in test['APPLICATION REQUIREMENTS COMPLETE']:
    if type(x)==pd._libs.tslibs.nattype.NaTType:
        appl_req_complete.append(0)
    else:    
        appl_req_complete.append(1)
test['APPLICATION REQUEST COMPLETE ENCODED']=appl_req_complete
test        

payment_date=[]
for x in test['PAYMENT DATE']:
    if type(x)==pd._libs.tslibs.nattype.NaTType:
        payment_date.append(0)
    else:    
        payment_date.append(1)
test['PAYMENT DATE ENCODED']=payment_date
test        

license_term_start=[]
for x in test['LICENSE TERM START DATE']:
    if type(x)==pd._libs.tslibs.nattype.NaTType:
        license_term_start.append(0)
    else:    
        license_term_start.append(1)
test['LICENSE TERM START DATE ENCODED']=license_term_start
test        

license_approved=[]
for x in test['LICENSE APPROVED FOR ISSUANCE']:
    if type(x)==pd._libs.tslibs.nattype.NaTType:
        license_approved.append(0)
    else:    
        license_approved.append(1)
test['LICENSE APPROVED FOR ISSUANCE ENCODED']=license_approved
test        

license_status_change=[]
for x in test['LICENSE STATUS CHANGE DATE']:
    if type(x)==pd._libs.tslibs.nattype.NaTType:
        license_status_change.append(0)
    else:    
        license_status_change.append(1)
test['LICENSE STATUS CHANGE DATE ENCODED']=license_status_change
test        




test['APPLICATION TYPE'].value_counts()

application_type=pd.get_dummies(test['APPLICATION TYPE'])

test=pd.concat([test,application_type],axis=1)

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED,LICENSE STATUS CHANGE DATE ENCODED
0,1516615-20120216,2132209,280120,1,RS HOMES I LLC,RS HOMES I LLC,350 W HUBBARD ST 3 300,CHICAGO,IL,60610.0,42.0,67.0,42-67,18.0,1020,Residential Real Estate Developer,1516615.0,RENEW,NaT,2011-12-15,2012-01-19,N,2012-02-16,2014-02-15,2012-01-19,2012-01-20,2012-12-29,NaN,41.890047,-87.637467,"{'latitude': '41.89004724888915', 'longitude':...",0,1,1,1,1,1
1,69813-20110616,2090759,65043,1,CSX INTERMODAL INC,CSX INTERMODAL,2101 W 59TH ST 1ST,CHICAGO,IL,60636.0,16.0,5.0,16-5,7.0,1010,Limited Business License,69813.0,RENEW,NaT,2011-04-15,2012-11-02,N,2011-06-16,2013-06-15,2012-11-02,2012-11-05,2012-12-29,NaN,41.786485,-87.676665,"{'latitude': '41.786485235679486', 'longitude'...",0,1,1,1,1,1
2,1519227-20041116,1541990,281270,1,LOCOMIBILE LOFTS LLC,LOCOMOBILE LOFTS LLC,1133 S WABASH AVE 1ST,CHICAGO,IL,60605.0,4.0,8.0,4-8,1.0,1020,Residential Real Estate Developer,1519227.0,RENEW,NaT,2004-09-27,2004-12-06,N,2004-11-16,2005-11-15,2004-12-06,2004-12-07,NaT,NaN,41.868269,-87.625695,"{'latitude': '41.86826924843568', 'longitude':...",0,1,1,1,1,0
3,1922025-20100816,2041053,335243,1,ANNA F. JAMISON,ANNA F. JAMISON,13156 S FORRESTVILLE AVE,CHICAGO,IL,60827.0,9.0,33.0,9-33,5.0,1607,"Peddler, non-food, special",1922025.0,RENEW,NaT,2010-06-15,2010-11-04,N,2010-08-16,2012-08-15,NaT,2010-11-04,2012-12-31,NaN,41.655762,-87.608686,"{'latitude': '41.65576175146191', 'longitude':...",0,1,1,1,0,1
4,1675683-20070816,1837158,283018,3,MARINCA A. COVARRUBIAS,DETAILS,4208 S ARCHER AVE,CHICAGO,IL,60632.0,15.0,26.0,15-26,9.0,1010,Limited Business License,1675683.0,RENEW,NaT,2007-06-21,2007-08-15,N,2007-08-16,2009-06-15,2007-08-15,2007-08-16,2008-03-26,39.0,41.816969,-87.699785,"{'latitude': '41.81696910012824', 'longitude':...",0,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57234,1743194-20070816,1835677,266103,3,"GOODHEALTH MEDICAL PRODUCTS, INC.","GOODHEALTH MEDICAL PRODUCTS, INC.",2621 W 79TH ST,CHICAGO,IL,60652.0,18.0,14.0,18-14,8.0,1010,Limited Business License,1743194.0,RENEW,NaT,2007-06-21,2007-09-12,N,2007-08-16,2009-11-15,2007-09-12,2007-09-18,2008-03-17,NaN,41.749842,-87.688733,"{'latitude': '41.74984206916219', 'longitude':...",0,1,1,1,1,1
57235,2032383-20160716,2465962,63376,180,INTERPARK LLC,INTERPARK,505 N STATE ST 2-4,CHICAGO,IL,60654.0,42.0,22.0,42-22,18.0,1002,Accessory Garage,2032383.0,RENEW,NaT,2016-05-15,2016-06-23,N,2016-07-16,2018-07-15,2016-06-23,2016-08-11,2018-01-09,NaN,41.891055,-87.627898,"{'latitude': '41.89105524147196', 'longitude':...",0,1,1,1,1,1
57236,40376-20020216,1211199,55051,1,YUN HEE HWANG,TOP CLEANERS,1201 W ROSCOE ST 1ST,CHICAGO,IL,60657.0,44.0,9.0,44-9,19.0,1010,Limited Business License,40376.0,RENEW,NaT,2001-12-20,2002-01-18,N,2002-02-16,2003-02-15,2002-01-18,2002-01-22,NaT,NaN,41.943382,-87.659191,"{'latitude': '41.94338183750669', 'longitude':...",0,1,1,1,1,0
57237,2064176-20121116,2188497,357381,1,D. C. A. TOWING INCORPORATED,D. C. A. TOWING INCORPORATED,7052 W 64TH ST 1ST,CHICAGO,IL,60638.0,23.0,18.0,23-18,8.0,1012,Home Occupation,2064176.0,RENEW,NaT,2012-09-14,2012-12-25,N,2012-11-16,2014-11-15,2012-12-25,2012-12-26,2012-12-29,NaN,41.775710,-87.798009,"{'latitude': '41.775709631013335', 'longitude'...",0,1,1,1,1,1
57238,1954052-20090202,1954052,340610,1,maria t bedoy,mari's cleaning services,4544 S CHRISTIANA AVE 1,CHICAGO,IL,60632.0,14.0,10.0,14-10,8.0,1012,Home Occupation,1954052.0,ISSUE,NaT,2009-01-31,2009-01-31,N,2009-02-02,2009-06-15,2009-01-31,2009-02-02,NaT,39.0,41.810523,-87.707872,"{'latitude': '41.81052250782054', 'longitude':...",0,1,1,1,1,0

In [108]:
application_type=pd.get_dummies(test['APPLICATION TYPE'])

test=pd.concat([test,application_type],axis=1)

legal_list=[]
for x in test['LEGAL NAME']:
    legal_list.append(x.split(' ')[-1])
    
legal_list

test['LEGAL TYPE']=legal_list

test['LEGAL TYPE'].value_counts()[:20]

test['LEGAL TYPE'].replace('INC.','INC',inplace=True)
test['LEGAL TYPE'].replace('Inc.','INC',inplace=True)
test['LEGAL TYPE'].replace('Inc','INC',inplace=True)
test['LEGAL TYPE'].replace('INCORPORATED','INC',inplace=True)


test['LEGAL TYPE'].value_counts()[:20]

test['LEGAL TYPE'].replace('L.L.C.','LLC',inplace=True)
test['LEGAL TYPE'].replace('llc','LLC',inplace=True)
test['LEGAL TYPE'].replace('llc.','LLC',inplace=True)
test['LEGAL TYPE'].replace('LLC.','LLC',inplace=True)
test['LEGAL TYPE'].replace('L.L.C','LLC',inplace=True)




test['LEGAL TYPE'].value_counts()[:20]

test['LEGAL TYPE'].replace('corp','CORPORATION',inplace=True)
test['LEGAL TYPE'].replace('CORP','CORPORATION',inplace=True)
test['LEGAL TYPE'].replace('CORP.','CORPORATION',inplace=True)
test['LEGAL TYPE'].replace('corp.','CORPORATION',inplace=True)
test['LEGAL TYPE'].replace('corporation','CORPORATION',inplace=True)


test['LEGAL TYPE'].value_counts()[:20]

test['LEGAL TYPE'].replace('co','COMPANY',inplace=True)
test['LEGAL TYPE'].replace('CO.','COMPANY',inplace=True)
test['LEGAL TYPE'].replace('company','COMPANY',inplace=True)
test['LEGAL TYPE'].replace('CO','COMPANY',inplace=True)
test['LEGAL TYPE'].replace('co.','COMPANY',inplace=True)


test['LEGAL TYPE'].value_counts()[:20]

test['LEGAL TYPE'].replace('LTD.','LTD',inplace=True)
test['LEGAL TYPE'].replace('ltd.','LTD',inplace=True)
test['LEGAL TYPE'].replace('ltd','LTD',inplace=True)
test['LEGAL TYPE'].replace('limited','LTD',inplace=True)
test['LEGAL TYPE'].replace('limited.','LTD',inplace=True)
test['LEGAL TYPE'].replace('LIMITED','LTD',inplace=True)
test['LEGAL TYPE'].replace('LIMITED.','LTD',inplace=True)


test['LEGAL TYPE'].value_counts()[:20]

test['LEGAL TYPE'].replace('SERVICE','SERVICES',inplace=True)
test['LEGAL TYPE'].replace('service','SERVICES',inplace=True)
test['LEGAL TYPE'].replace('services','SERVICES',inplace=True)


test['LEGAL TYPE'].value_counts()[:20]

### so the top five value counts have significant numbers, thus it makes sense in encoding them, rest can reflect 0

legal_type_list=[]
for x in test['LEGAL TYPE']:
    if x not in ['INC','CORPORATION','LLC','COMPANY','LTD']:
        legal_type_list.append('OTHER')
    else:
        legal_type_list.append(x)
    

legal_type_list
len(legal_type_list)

test['LEGAL TYPE CLASSIFIED']=legal_type_list

test

### getting dummies from the "legal type classifed" column

legal_dummies=pd.get_dummies(test['LEGAL TYPE CLASSIFIED'],drop_first=True)

legal_dummies

test=pd.concat([test,legal_dummies],axis=1)

test.head()

site_number_list=[]
for x in test['SITE NUMBER']:
    if x not in [1,2,3,4]:
        site_number_list.append('OTHER SITE')
    else:
        site_number_list.append(x)

site_number_list

test['SITE NUMBER ENCODED']=site_number_list

site_dummies=pd.get_dummies(test['SITE NUMBER ENCODED'],drop_first=True)
site_dummies

test=pd.concat([test,site_dummies],axis=1)

test.head()

### i will now be encoding the "license code" column

license_code_list=[]
for x in test['LICENSE CODE']:
    if x not in [1010,1011,1012,1006,1525,1676,1008,1020]:
        license_code_list.append('OTHER LICENSE CODE')
    else:
        license_code_list.append(x)

test['LICENSE CODE ENCODED']=license_code_list
test

license_code_dummy=pd.get_dummies(test['LICENSE CODE ENCODED'],drop_first=True)

test=pd.concat([test,license_code_dummy],axis=1)
test

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED,LICENSE STATUS CHANGE DATE ENCODED,C_CAPA,C_EXPA,C_LOC,C_SBA,ISSUE,RENEW,LEGAL TYPE,LEGAL TYPE CLASSIFIED,CORPORATION,INC,LLC,LTD,OTHER,SITE NUMBER ENCODED,2,3,4,OTHER SITE,LICENSE CODE ENCODED,1008,1010,1011,1012,1020,1525,1676,OTHER LICENSE CODE
0,1516615-20120216,2132209,280120,1,RS HOMES I LLC,RS HOMES I LLC,350 W HUBBARD ST 3 300,CHICAGO,IL,60610.0,42.0,67.0,42-67,18.0,1020,Residential Real Estate Developer,1516615.0,RENEW,NaT,2011-12-15,2012-01-19,N,2012-02-16,2014-02-15,2012-01-19,2012-01-20,2012-12-29,NaN,41.890047,-87.637467,"{'latitude': '41.89004724888915', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,LLC,LLC,0,0,1,0,0,1,0,0,0,0,1020,0,0,0,0,1,0,0,0
1,69813-20110616,2090759,65043,1,CSX INTERMODAL INC,CSX INTERMODAL,2101 W 59TH ST 1ST,CHICAGO,IL,60636.0,16.0,5.0,16-5,7.0,1010,Limited Business License,69813.0,RENEW,NaT,2011-04-15,2012-11-02,N,2011-06-16,2013-06-15,2012-11-02,2012-11-05,2012-12-29,NaN,41.786485,-87.676665,"{'latitude': '41.786485235679486', 'longitude'...",0,1,1,1,1,1,0,0,0,0,0,1,INC,INC,0,1,0,0,0,1,0,0,0,0,1010,0,1,0,0,0,0,0,0
2,1519227-20041116,1541990,281270,1,LOCOMIBILE LOFTS LLC,LOCOMOBILE LOFTS LLC,1133 S WABASH AVE 1ST,CHICAGO,IL,60605.0,4.0,8.0,4-8,1.0,1020,Residential Real Estate Developer,1519227.0,RENEW,NaT,2004-09-27,2004-12-06,N,2004-11-16,2005-11-15,2004-12-06,2004-12-07,NaT,NaN,41.868269,-87.625695,"{'latitude': '41.86826924843568', 'longitude':...",0,1,1,1,1,0,0,0,0,0,0,1,LLC,LLC,0,0,1,0,0,1,0,0,0,0,1020,0,0,0,0,1,0,0,0
3,1922025-20100816,2041053,335243,1,ANNA F. JAMISON,ANNA F. JAMISON,13156 S FORRESTVILLE AVE,CHICAGO,IL,60827.0,9.0,33.0,9-33,5.0,1607,"Peddler, non-food, special",1922025.0,RENEW,NaT,2010-06-15,2010-11-04,N,2010-08-16,2012-08-15,NaT,2010-11-04,2012-12-31,NaN,41.655762,-87.608686,"{'latitude': '41.65576175146191', 'longitude':...",0,1,1,1,0,1,0,0,0,0,0,1,JAMISON,OTHER,0,0,0,0,1,1,0,0,0,0,OTHER LICENSE CODE,0,0,0,0,0,0,0,1
4,1675683-20070816,1837158,283018,3,MARINCA A. COVARRUBIAS,DETAILS,4208 S ARCHER AVE,CHICAGO,IL,60632.0,15.0,26.0,15-26,9.0,1010,Limited Business License,1675683.0,RENEW,NaT,2007-06-21,2007-08-15,N,2007-08-16,2009-06-15,2007-08-15,2007-08-16,2008-03-26,39.0,41.816969,-87.699785,"{'latitude': '41.81696910012824', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,COVARRUBIAS,OTHER,0,0,0,0,1,3,0,1,0,0,1010,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57234,1743194-20070816,1835677,266103,3,"GOODHEALTH MEDICAL PRODUCTS, INC.","GOODHEALTH MEDICAL PRODUCTS, INC.",2621 W 79TH ST,CHICAGO,IL,60652.0,18.0,14.0,18-14,8.0,1010,Limited Business License,1743194.0,RENEW,NaT,2007-06-21,2007-09-12,N,2007-08-16,2009-11-15,2007-09-12,2007-09-18,2008-03-17,NaN,41.749842,-87.688733,"{'latitude': '41.74984206916219', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,INC,INC,0,1,0,0,0,3,0,1,0,0,1010,0,1,0,0,0,0,0,0
57235,2032383-20160716,2465962,63376,180,INTERPARK LLC,INTERPARK,505 N STATE ST 2-4,CHICAGO,IL,60654.0,42.0,22.0,42-22,18.0,1002,Accessory Garage,2032383.0,RENEW,NaT,2016-05-15,2016-06-23,N,2016-07-16,2018-07-15,2016-06-23,2016-08-11,2018-01-09,NaN,41.891055,-87.627898,"{'latitude': '41.89105524147196', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,LLC,LLC,0,0,1,0,0,OTHER SITE,0,0,0,1,OTHER LICENSE CODE,0,0,0,0,0,0,0,1
57236,40376-20020216,1211199,55051,1,YUN HEE HWANG,TOP CLEANERS,1201 W ROSCOE ST 1ST,CHICAGO,IL,60657.0,44.0,9.0,44-9,19.0,1010,Limited Business License,40376.0,RENEW,NaT,2001-12-20,2002-01-18,N,2002-02-16,2003-02-15,2002-01-18,2002-01-22,NaT,NaN,41.943382,-87.659191,"{'latitude': '41.94338183750669', 'longitude':...",0,1,1,1,1,0,0,0,0,0,0,1,HWANG,OTHER,0,0,0,0,1,1,0,0,0,0,1010,0,1,0,0,0,0,0,0
57237,2064176-20121116,2188497,357381,1,D. C. A. TOWING INCORPORATED,D. C. A. TOWING INCORPORATED,7052 W 64TH ST 1ST,CHICAGO,IL,60638.0,23.0,18.0,23-18,8.0,1012,Home Occupation,2064176.0,RENEW,NaT,2012-09-14,2012-12-25,N,2012-11-16,2014-11-15,2012-12-25,2012-12-26,2012-12-29,NaN,41.775710,-87.798009,"{'latitude': '41.775709631013335', 'longitude'...",0,1,1,1,1,1,0,0,0,0,0,1,INC,INC,0,1,0,0,0,1,0,0,0,0,1012,0,0,0,1,0,0,0,0
57238,1954052-20090202,1954052,340610,1,maria t bedoy,mari's cleaning services,4544 S CHRISTIANA AVE 1,CHICAGO,IL,60632.0,14.0,10.0,14-10,8.0,1012,Home Occupation,1954052.0,ISSUE,NaT,2009-01-31,2009-01-31,N,2009-02-02,2009-06-15,2009-01-31,2009-02-02,NaT,39.0,41.810523,-87.707872,"{'latitude': '41.81052250782054', 'longitude':...",0,1,1,1,1,0,0,0,0,0,1,0,bedoy,OTHER,0,0,0,0,1,1,0,0,0,0,1012,0,0,0,1,0,0,0,0

In [63]:
application_type=pd.get_dummies(df['APPLICATION TYPE'])

df=pd.concat([df,application_type],axis=1)

In [64]:
legal_list=[]
for x in df['LEGAL NAME']:
    legal_list.append(x.split(' ')[-1])
    
legal_list

df['LEGAL TYPE']=legal_list

df['LEGAL TYPE'].value_counts()[:20]

df['LEGAL TYPE'].replace('INC.','INC',inplace=True)
df['LEGAL TYPE'].replace('Inc.','INC',inplace=True)
df['LEGAL TYPE'].replace('Inc','INC',inplace=True)
df['LEGAL TYPE'].replace('INCORPORATED','INC',inplace=True)


df['LEGAL TYPE'].value_counts()[:20]

df['LEGAL TYPE'].replace('L.L.C.','LLC',inplace=True)
df['LEGAL TYPE'].replace('llc','LLC',inplace=True)
df['LEGAL TYPE'].replace('llc.','LLC',inplace=True)
df['LEGAL TYPE'].replace('LLC.','LLC',inplace=True)
df['LEGAL TYPE'].replace('L.L.C','LLC',inplace=True)




df['LEGAL TYPE'].value_counts()[:20]

df['LEGAL TYPE'].replace('corp','CORPORATION',inplace=True)
df['LEGAL TYPE'].replace('CORP','CORPORATION',inplace=True)
df['LEGAL TYPE'].replace('CORP.','CORPORATION',inplace=True)
df['LEGAL TYPE'].replace('corp.','CORPORATION',inplace=True)
df['LEGAL TYPE'].replace('corporation','CORPORATION',inplace=True)


df['LEGAL TYPE'].value_counts()[:20]

df['LEGAL TYPE'].replace('co','COMPANY',inplace=True)
df['LEGAL TYPE'].replace('CO.','COMPANY',inplace=True)
df['LEGAL TYPE'].replace('company','COMPANY',inplace=True)
df['LEGAL TYPE'].replace('CO','COMPANY',inplace=True)
df['LEGAL TYPE'].replace('co.','COMPANY',inplace=True)


df['LEGAL TYPE'].value_counts()[:20]

df['LEGAL TYPE'].replace('LTD.','LTD',inplace=True)
df['LEGAL TYPE'].replace('ltd.','LTD',inplace=True)
df['LEGAL TYPE'].replace('ltd','LTD',inplace=True)
df['LEGAL TYPE'].replace('limited','LTD',inplace=True)
df['LEGAL TYPE'].replace('limited.','LTD',inplace=True)
df['LEGAL TYPE'].replace('LIMITED','LTD',inplace=True)
df['LEGAL TYPE'].replace('LIMITED.','LTD',inplace=True)


df['LEGAL TYPE'].value_counts()[:20]

df['LEGAL TYPE'].replace('SERVICE','SERVICES',inplace=True)
df['LEGAL TYPE'].replace('service','SERVICES',inplace=True)
df['LEGAL TYPE'].replace('services','SERVICES',inplace=True)


df['LEGAL TYPE'].value_counts()[:20]

### so the top five value counts have significant numbers, thus it makes sense in encoding them, rest can reflect 0

legal_type_list=[]
for x in df['LEGAL TYPE']:
    if x not in ['INC','CORPORATION','LLC','COMPANY','LTD']:
        legal_type_list.append('OTHER')
    else:
        legal_type_list.append(x)
    

legal_type_list
len(legal_type_list)

df['LEGAL TYPE CLASSIFIED']=legal_type_list

df

### getting dummies from the "legal type classifed" column

legal_dummies=pd.get_dummies(df['LEGAL TYPE CLASSIFIED'],drop_first=True)

legal_dummies

df=pd.concat([df,legal_dummies],axis=1)

df.head()

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED,LICENSE STATUS CHANGE DATE ENCODED,C_CAPA,C_EXPA,C_LOC,ISSUE,RENEW,LEGAL TYPE,LEGAL TYPE CLASSIFIED,CORPORATION,INC,LLC,LTD,OTHER
0,35342-20020816,1256593,32811,1,CARMEN CAHUE,CLAUDIA'S BRIDAL SHOP,2625 S CENTRAL PARK AVE 1,CHICAGO,IL,60623.0,22.0,28.0,22-28,10.0,1010,Limited Business License,35342.0,RENEW,NaT,2002-06-28,2002-08-21,N,2002-08-16,2003-08-15,2002-08-21,2006-04-11,NaT,25.0,41.843613,-87.714618,"{'latitude': '41.843612879431845', 'longitude'...",AAI,0,1,1,1,1,0,0,0,0,0,1,CAHUE,OTHER,0,0,0,0,1
1,1358463-20051116,1639294,262311,29,"ISLA TROPICAL, INC.",ISLA TROPICAL,2825 W MONTROSE AVE,CHICAGO,IL,60618,33.0,23.0,33-23,17.0,1315,Mobile Food Dispenser,1358463.0,RENEW,NaT,2005-09-22,2005-11-03,N,2005-11-16,2006-11-15,2006-04-05,2006-06-12,2006-06-15,60.0,41.961132,-87.699626,"{'latitude': '41.96113244107215', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,INC,INC,0,1,0,0,0
2,1980233-20090722,1980233,345008,1,DJS REMODELING,"DJS REMODELING, INC.",1605 CLAVEY RD 1,HIGHLAND,IL,60035,NaN,NaN,NaN,NaN,1011,Home Repair,1980233.0,ISSUE,2009-06-29,2009-07-22,2009-07-22,N,2009-07-22,2011-07-15,2009-07-22,2009-07-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,REMODELING,OTHER,0,0,0,0,1
3,1476582-20040211,1476582,273121,1,ALL-BRY CONSTRUCTION CO.,ALL-BRY CONSTRUCTION CO.,8 NORTH TRAIL,LEMONT,IL,60439,NaN,NaN,NaN,NaN,1010,Limited Business License,1476582.0,ISSUE,2004-02-10,2004-02-10,2004-02-10,N,2004-02-11,2005-02-15,2004-02-10,2004-02-11,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,COMPANY,COMPANY,0,0,0,0,0
4,1141408-20080516,1896750,213785,1,MCDONOUGH MECHANICAL SERVICE,MCDONOUGH MECHANICAL SERVICE,4081 JOSEPH DR,WAUKEGAN,IL,60087,NaN,NaN,NaN,NaN,1010,Limited Business License,1141408.0,RENEW,NaT,2008-03-24,2008-06-04,N,2008-05-16,2010-05-15,2008-06-04,2008-06-05,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1,1,0,0,0,0,0,1,SERVICES,OTHER,0,0,0,0,1

In [65]:
site_number_list=[]
for x in df['SITE NUMBER']:
    if x not in [1,2,3,4]:
        site_number_list.append('OTHER SITE')
    else:
        site_number_list.append(x)

site_number_list

df['SITE NUMBER ENCODED']=site_number_list

site_dummies=pd.get_dummies(df['SITE NUMBER ENCODED'],drop_first=True)
site_dummies

df=pd.concat([df,site_dummies],axis=1)

df.head()

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED,LICENSE STATUS CHANGE DATE ENCODED,C_CAPA,C_EXPA,C_LOC,ISSUE,RENEW,LEGAL TYPE,LEGAL TYPE CLASSIFIED,CORPORATION,INC,LLC,LTD,OTHER,SITE NUMBER ENCODED,2,3,4,OTHER SITE
0,35342-20020816,1256593,32811,1,CARMEN CAHUE,CLAUDIA'S BRIDAL SHOP,2625 S CENTRAL PARK AVE 1,CHICAGO,IL,60623.0,22.0,28.0,22-28,10.0,1010,Limited Business License,35342.0,RENEW,NaT,2002-06-28,2002-08-21,N,2002-08-16,2003-08-15,2002-08-21,2006-04-11,NaT,25.0,41.843613,-87.714618,"{'latitude': '41.843612879431845', 'longitude'...",AAI,0,1,1,1,1,0,0,0,0,0,1,CAHUE,OTHER,0,0,0,0,1,1,0,0,0,0
1,1358463-20051116,1639294,262311,29,"ISLA TROPICAL, INC.",ISLA TROPICAL,2825 W MONTROSE AVE,CHICAGO,IL,60618,33.0,23.0,33-23,17.0,1315,Mobile Food Dispenser,1358463.0,RENEW,NaT,2005-09-22,2005-11-03,N,2005-11-16,2006-11-15,2006-04-05,2006-06-12,2006-06-15,60.0,41.961132,-87.699626,"{'latitude': '41.96113244107215', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,INC,INC,0,1,0,0,0,OTHER SITE,0,0,0,1
2,1980233-20090722,1980233,345008,1,DJS REMODELING,"DJS REMODELING, INC.",1605 CLAVEY RD 1,HIGHLAND,IL,60035,NaN,NaN,NaN,NaN,1011,Home Repair,1980233.0,ISSUE,2009-06-29,2009-07-22,2009-07-22,N,2009-07-22,2011-07-15,2009-07-22,2009-07-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,REMODELING,OTHER,0,0,0,0,1,1,0,0,0,0
3,1476582-20040211,1476582,273121,1,ALL-BRY CONSTRUCTION CO.,ALL-BRY CONSTRUCTION CO.,8 NORTH TRAIL,LEMONT,IL,60439,NaN,NaN,NaN,NaN,1010,Limited Business License,1476582.0,ISSUE,2004-02-10,2004-02-10,2004-02-10,N,2004-02-11,2005-02-15,2004-02-10,2004-02-11,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,COMPANY,COMPANY,0,0,0,0,0,1,0,0,0,0
4,1141408-20080516,1896750,213785,1,MCDONOUGH MECHANICAL SERVICE,MCDONOUGH MECHANICAL SERVICE,4081 JOSEPH DR,WAUKEGAN,IL,60087,NaN,NaN,NaN,NaN,1010,Limited Business License,1141408.0,RENEW,NaT,2008-03-24,2008-06-04,N,2008-05-16,2010-05-15,2008-06-04,2008-06-05,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1,1,0,0,0,0,0,1,SERVICES,OTHER,0,0,0,0,1,1,0,0,0,0

In [66]:
### i will now be encoding the "license code" column

license_code_list=[]
for x in df['LICENSE CODE']:
    if x not in [1010,1011,1012,1006,1525,1676,1008,1020]:
        license_code_list.append('OTHER LICENSE CODE')
    else:
        license_code_list.append(x)

df['LICENSE CODE ENCODED']=license_code_list
df

license_code_dummy=pd.get_dummies(df['LICENSE CODE ENCODED'],drop_first=True)

df=pd.concat([df,license_code_dummy],axis=1)
df

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,LICENSE STATUS,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED,LICENSE STATUS CHANGE DATE ENCODED,C_CAPA,C_EXPA,C_LOC,ISSUE,RENEW,LEGAL TYPE,LEGAL TYPE CLASSIFIED,CORPORATION,INC,LLC,LTD,OTHER,SITE NUMBER ENCODED,2,3,4,OTHER SITE,LICENSE CODE ENCODED,1008,1010,1011,1012,1020,1525,1676,OTHER LICENSE CODE
0,35342-20020816,1256593,32811,1,CARMEN CAHUE,CLAUDIA'S BRIDAL SHOP,2625 S CENTRAL PARK AVE 1,CHICAGO,IL,60623.0,22.0,28.0,22-28,10.0,1010,Limited Business License,35342.0,RENEW,NaT,2002-06-28,2002-08-21,N,2002-08-16,2003-08-15,2002-08-21,2006-04-11,NaT,25.0,41.843613,-87.714618,"{'latitude': '41.843612879431845', 'longitude'...",AAI,0,1,1,1,1,0,0,0,0,0,1,CAHUE,OTHER,0,0,0,0,1,1,0,0,0,0,1010,0,1,0,0,0,0,0,0
1,1358463-20051116,1639294,262311,29,"ISLA TROPICAL, INC.",ISLA TROPICAL,2825 W MONTROSE AVE,CHICAGO,IL,60618,33.0,23.0,33-23,17.0,1315,Mobile Food Dispenser,1358463.0,RENEW,NaT,2005-09-22,2005-11-03,N,2005-11-16,2006-11-15,2006-04-05,2006-06-12,2006-06-15,60.0,41.961132,-87.699626,"{'latitude': '41.96113244107215', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,INC,INC,0,1,0,0,0,OTHER SITE,0,0,0,1,OTHER LICENSE CODE,0,0,0,0,0,0,0,1
2,1980233-20090722,1980233,345008,1,DJS REMODELING,"DJS REMODELING, INC.",1605 CLAVEY RD 1,HIGHLAND,IL,60035,NaN,NaN,NaN,NaN,1011,Home Repair,1980233.0,ISSUE,2009-06-29,2009-07-22,2009-07-22,N,2009-07-22,2011-07-15,2009-07-22,2009-07-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,REMODELING,OTHER,0,0,0,0,1,1,0,0,0,0,1011,0,0,1,0,0,0,0,0
3,1476582-20040211,1476582,273121,1,ALL-BRY CONSTRUCTION CO.,ALL-BRY CONSTRUCTION CO.,8 NORTH TRAIL,LEMONT,IL,60439,NaN,NaN,NaN,NaN,1010,Limited Business License,1476582.0,ISSUE,2004-02-10,2004-02-10,2004-02-10,N,2004-02-11,2005-02-15,2004-02-10,2004-02-11,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,COMPANY,COMPANY,0,0,0,0,0,1,0,0,0,0,1010,0,1,0,0,0,0,0,0
4,1141408-20080516,1896750,213785,1,MCDONOUGH MECHANICAL SERVICE,MCDONOUGH MECHANICAL SERVICE,4081 JOSEPH DR,WAUKEGAN,IL,60087,NaN,NaN,NaN,NaN,1010,Limited Business License,1141408.0,RENEW,NaT,2008-03-24,2008-06-04,N,2008-05-16,2010-05-15,2008-06-04,2008-06-05,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1,1,0,0,0,0,0,1,SERVICES,OTHER,0,0,0,0,1,1,0,0,0,0,1010,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85890,12652-20120516,2143400,8011,1,UNITED PARCEL SERVICE,UNITED PARCEL SERVICE,1400 S JEFFERSON ST,CHICAGO,IL,60607.0,11.0,28.0,11-28,1.0,1008,Hazardous Materials,12652.0,RENEW,NaT,2012-03-15,2012-05-07,N,2012-05-16,2014-05-15,2012-05-07,2012-05-08,2012-12-29,NaN,41.863501,-87.642210,"{'latitude': '41.86350135244771', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,SERVICES,OTHER,0,0,0,0,1,1,0,0,0,0,1008,1,0,0,0,0,0,0,0
85891,1821421-20070522,1821421,317725,1,"EXPRESS BOARD UP SERVICE, INC.","EXPRESS BOARD UP SERVICE, INC.",8707 VANGUARD DR,MACHESNEY PARK,IL,61115.0,NaN,NaN,NaN,NaN,1800,Board-Up Work,1821421.0,ISSUE,2007-05-21,2007-05-22,2007-05-22,N,2007-05-22,2009-06-15,2007-05-22,2007-05-22,NaT,NaN,NaN,NaN,NaN,AAI,1,1,1,1,1,0,0,0,0,1,0,INC,INC,0,1,0,0,0,1,0,0,0,0,OTHER LICENSE CODE,0,0,0,0,0,0,0,1
85892,74137-20090116,1939358,8458,2,ARAMARK SMMS LLC,ARAMARK FACILITY SERVICES,2300 WARRENVILLE RD 1ST,DOWNERS GROVE,IL,60515.0,NaN,NaN,NaN,NaN,1010,Limited Business License,74137.0,RENEW,NaT,2008-11-14,2009-01-09,N,2009-01-16,2011-01-15,2009-01-09,2009-12-08,NaT,NaN,NaN,NaN,NaN,AAI,0,1,1,1,1,0,0,0,0,0,1,LLC,LLC,0,0,1,0,0,2,1,0,0,0,1010,0,1,0,0,0,0,0,0
85893,2049545-20111016,2110060,2156,43,GENERAL NUTRITION CORPORATION,GENERAL NUTRITION CENTER # 61,5151 S PULASKI RD SLAB ON GRADE T-21,CHICAGO,IL,60632.0,23.0,NaN,23-,NaN,1010,Limited Business License,2049545.0,RENEW,NaT,2011-08-15,2011-10-03,N,2011-10-16,2013-10-15,2011-10-03,2011-10-11,2012-05-08,NaN,41.799012,-87.723181,"{'latitude': '41.79901235310339', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,CORPORATION,CORPORATION,1,0,0,0,0,OTHER SITE,0,0,0,1,1010,0,1,0,0,0,0,0,0
85894,1070196-20040216,1461628,205936,1,JUAN CARLOS ERAZO,CASA DE JUAN RESTAURANT,5814 W FULLERTON AVE,CHICAGO,IL,60639.0,30.0,52.0,30-52,25.0,1006,Retail Food Establishment,1070196.0,RENEW,NaT,2003-12-15,2004-02-06,N,2004-02-16,2005-02-15,2003-12-22,2004-02-09,2005-01-07,NaN,41.924004,-87.771507,"{'latitude': '41.92400390449922', 'longitude':...",AAC,0,1,1,1,1,1,0,0,0,0,1,ERAZO,OTHER,0,0,0,0,1,1,0,0,0,0,1006,0,0,0,0,0,0,0,0

In [109]:
test

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED,LICENSE STATUS CHANGE DATE ENCODED,C_CAPA,C_EXPA,C_LOC,C_SBA,ISSUE,RENEW,LEGAL TYPE,LEGAL TYPE CLASSIFIED,CORPORATION,INC,LLC,LTD,OTHER,SITE NUMBER ENCODED,2,3,4,OTHER SITE,LICENSE CODE ENCODED,1008,1010,1011,1012,1020,1525,1676,OTHER LICENSE CODE
0,1516615-20120216,2132209,280120,1,RS HOMES I LLC,RS HOMES I LLC,350 W HUBBARD ST 3 300,CHICAGO,IL,60610.0,42.0,67.0,42-67,18.0,1020,Residential Real Estate Developer,1516615.0,RENEW,NaT,2011-12-15,2012-01-19,N,2012-02-16,2014-02-15,2012-01-19,2012-01-20,2012-12-29,NaN,41.890047,-87.637467,"{'latitude': '41.89004724888915', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,LLC,LLC,0,0,1,0,0,1,0,0,0,0,1020,0,0,0,0,1,0,0,0
1,69813-20110616,2090759,65043,1,CSX INTERMODAL INC,CSX INTERMODAL,2101 W 59TH ST 1ST,CHICAGO,IL,60636.0,16.0,5.0,16-5,7.0,1010,Limited Business License,69813.0,RENEW,NaT,2011-04-15,2012-11-02,N,2011-06-16,2013-06-15,2012-11-02,2012-11-05,2012-12-29,NaN,41.786485,-87.676665,"{'latitude': '41.786485235679486', 'longitude'...",0,1,1,1,1,1,0,0,0,0,0,1,INC,INC,0,1,0,0,0,1,0,0,0,0,1010,0,1,0,0,0,0,0,0
2,1519227-20041116,1541990,281270,1,LOCOMIBILE LOFTS LLC,LOCOMOBILE LOFTS LLC,1133 S WABASH AVE 1ST,CHICAGO,IL,60605.0,4.0,8.0,4-8,1.0,1020,Residential Real Estate Developer,1519227.0,RENEW,NaT,2004-09-27,2004-12-06,N,2004-11-16,2005-11-15,2004-12-06,2004-12-07,NaT,NaN,41.868269,-87.625695,"{'latitude': '41.86826924843568', 'longitude':...",0,1,1,1,1,0,0,0,0,0,0,1,LLC,LLC,0,0,1,0,0,1,0,0,0,0,1020,0,0,0,0,1,0,0,0
3,1922025-20100816,2041053,335243,1,ANNA F. JAMISON,ANNA F. JAMISON,13156 S FORRESTVILLE AVE,CHICAGO,IL,60827.0,9.0,33.0,9-33,5.0,1607,"Peddler, non-food, special",1922025.0,RENEW,NaT,2010-06-15,2010-11-04,N,2010-08-16,2012-08-15,NaT,2010-11-04,2012-12-31,NaN,41.655762,-87.608686,"{'latitude': '41.65576175146191', 'longitude':...",0,1,1,1,0,1,0,0,0,0,0,1,JAMISON,OTHER,0,0,0,0,1,1,0,0,0,0,OTHER LICENSE CODE,0,0,0,0,0,0,0,1
4,1675683-20070816,1837158,283018,3,MARINCA A. COVARRUBIAS,DETAILS,4208 S ARCHER AVE,CHICAGO,IL,60632.0,15.0,26.0,15-26,9.0,1010,Limited Business License,1675683.0,RENEW,NaT,2007-06-21,2007-08-15,N,2007-08-16,2009-06-15,2007-08-15,2007-08-16,2008-03-26,39.0,41.816969,-87.699785,"{'latitude': '41.81696910012824', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,COVARRUBIAS,OTHER,0,0,0,0,1,3,0,1,0,0,1010,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57234,1743194-20070816,1835677,266103,3,"GOODHEALTH MEDICAL PRODUCTS, INC.","GOODHEALTH MEDICAL PRODUCTS, INC.",2621 W 79TH ST,CHICAGO,IL,60652.0,18.0,14.0,18-14,8.0,1010,Limited Business License,1743194.0,RENEW,NaT,2007-06-21,2007-09-12,N,2007-08-16,2009-11-15,2007-09-12,2007-09-18,2008-03-17,NaN,41.749842,-87.688733,"{'latitude': '41.74984206916219', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,INC,INC,0,1,0,0,0,3,0,1,0,0,1010,0,1,0,0,0,0,0,0
57235,2032383-20160716,2465962,63376,180,INTERPARK LLC,INTERPARK,505 N STATE ST 2-4,CHICAGO,IL,60654.0,42.0,22.0,42-22,18.0,1002,Accessory Garage,2032383.0,RENEW,NaT,2016-05-15,2016-06-23,N,2016-07-16,2018-07-15,2016-06-23,2016-08-11,2018-01-09,NaN,41.891055,-87.627898,"{'latitude': '41.89105524147196', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,LLC,LLC,0,0,1,0,0,OTHER SITE,0,0,0,1,OTHER LICENSE CODE,0,0,0,0,0,0,0,1
57236,40376-20020216,1211199,55051,1,YUN HEE HWANG,TOP CLEANERS,1201 W ROSCOE ST 1ST,CHICAGO,IL,60657.0,44.0,9.0,44-9,19.0,1010,Limited Business License,40376.0,RENEW,NaT,2001-12-20,2002-01-18,N,2002-02-16,2003-02-15,2002-01-18,2002-01-22,NaT,NaN,41.943382,-87.659191,"{'latitude': '41.94338183750669', 'longitude':...",0,1,1,1,1,0,0,0,0,0,0,1,HWANG,OTHER,0,0,0,0,1,1,0,0,0,0,1010,0,1,0,0,0,0,0,0
57237,2064176-20121116,2188497,357381,1,D. C. A. TOWING INCORPORATED,D. C. A. TOWING INCORPORATED,7052 W 64TH ST 1ST,CHICAGO,IL,60638.0,23.0,18.0,23-18,8.0,1012,Home Occupation,2064176.0,RENEW,NaT,2012-09-14,2012-12-25,N,2012-11-16,2014-11-15,2012-12-25,2012-12-26,2012-12-29,NaN,41.775710,-87.798009,"{'latitude': '41.775709631013335', 'longitude'...",0,1,1,1,1,1,0,0,0,0,0,1,INC,INC,0,1,0,0,0,1,0,0,0,0,1012,0,0,0,1,0,0,0,0
57238,1954052-20090202,1954052,340610,1,maria t bedoy,mari's cleaning services,4544 S CHRISTIANA AVE 1,CHICAGO,IL,60632.0,14.0,10.0,14-10,8.0,1012,Home Occupation,1954052.0,ISSUE,NaT,2009-01-31,2009-01-31,N,2009-02-02,2009-06-15,2009-01-31,2009-02-02,NaT,39.0,41.810523,-87.707872,"{'latitude': '41.81052250782054', 'longitude':...",0,1,1,1,1,0,0,0,0,0,1,0,bedoy,OTHER,0,0,0,0,1,1,0,0,0,0,1012,0,0,0,1,0,0,0,0

In [110]:
### encoding license description 

license_description_list=[]
for x in test['LICENSE DESCRIPTION']:
    if x not in ['Limited Business License','Home Repair','Home Occupation','Retail Food Establishment','Massage Therapist','Scavenger, Private','Hazardous Materials','Residential Real Estate Developer']:
        license_description_list.append('OTHER LICENSE DESC')
    else:
        license_description_list.append(x)

license_description_list

test['LICENSE DESCRIPTION ENCODED']=license_description_list
test

license_description_dummy=pd.get_dummies(test['LICENSE DESCRIPTION ENCODED'])

test=pd.concat([test,license_description_dummy],axis=1)

test

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED,LICENSE STATUS CHANGE DATE ENCODED,C_CAPA,C_EXPA,C_LOC,C_SBA,ISSUE,RENEW,LEGAL TYPE,LEGAL TYPE CLASSIFIED,CORPORATION,INC,LLC,LTD,OTHER,SITE NUMBER ENCODED,2,3,4,OTHER SITE,LICENSE CODE ENCODED,1008,1010,1011,1012,1020,1525,1676,OTHER LICENSE CODE,LICENSE DESCRIPTION ENCODED,Hazardous Materials,Home Occupation,Home Repair,Limited Business License,Massage Therapist,OTHER LICENSE DESC,Residential Real Estate Developer,Retail Food Establishment,"Scavenger, Private"
0,1516615-20120216,2132209,280120,1,RS HOMES I LLC,RS HOMES I LLC,350 W HUBBARD ST 3 300,CHICAGO,IL,60610.0,42.0,67.0,42-67,18.0,1020,Residential Real Estate Developer,1516615.0,RENEW,NaT,2011-12-15,2012-01-19,N,2012-02-16,2014-02-15,2012-01-19,2012-01-20,2012-12-29,NaN,41.890047,-87.637467,"{'latitude': '41.89004724888915', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,LLC,LLC,0,0,1,0,0,1,0,0,0,0,1020,0,0,0,0,1,0,0,0,Residential Real Estate Developer,0,0,0,0,0,0,1,0,0
1,69813-20110616,2090759,65043,1,CSX INTERMODAL INC,CSX INTERMODAL,2101 W 59TH ST 1ST,CHICAGO,IL,60636.0,16.0,5.0,16-5,7.0,1010,Limited Business License,69813.0,RENEW,NaT,2011-04-15,2012-11-02,N,2011-06-16,2013-06-15,2012-11-02,2012-11-05,2012-12-29,NaN,41.786485,-87.676665,"{'latitude': '41.786485235679486', 'longitude'...",0,1,1,1,1,1,0,0,0,0,0,1,INC,INC,0,1,0,0,0,1,0,0,0,0,1010,0,1,0,0,0,0,0,0,Limited Business License,0,0,0,1,0,0,0,0,0
2,1519227-20041116,1541990,281270,1,LOCOMIBILE LOFTS LLC,LOCOMOBILE LOFTS LLC,1133 S WABASH AVE 1ST,CHICAGO,IL,60605.0,4.0,8.0,4-8,1.0,1020,Residential Real Estate Developer,1519227.0,RENEW,NaT,2004-09-27,2004-12-06,N,2004-11-16,2005-11-15,2004-12-06,2004-12-07,NaT,NaN,41.868269,-87.625695,"{'latitude': '41.86826924843568', 'longitude':...",0,1,1,1,1,0,0,0,0,0,0,1,LLC,LLC,0,0,1,0,0,1,0,0,0,0,1020,0,0,0,0,1,0,0,0,Residential Real Estate Developer,0,0,0,0,0,0,1,0,0
3,1922025-20100816,2041053,335243,1,ANNA F. JAMISON,ANNA F. JAMISON,13156 S FORRESTVILLE AVE,CHICAGO,IL,60827.0,9.0,33.0,9-33,5.0,1607,"Peddler, non-food, special",1922025.0,RENEW,NaT,2010-06-15,2010-11-04,N,2010-08-16,2012-08-15,NaT,2010-11-04,2012-12-31,NaN,41.655762,-87.608686,"{'latitude': '41.65576175146191', 'longitude':...",0,1,1,1,0,1,0,0,0,0,0,1,JAMISON,OTHER,0,0,0,0,1,1,0,0,0,0,OTHER LICENSE CODE,0,0,0,0,0,0,0,1,OTHER LICENSE DESC,0,0,0,0,0,1,0,0,0
4,1675683-20070816,1837158,283018,3,MARINCA A. COVARRUBIAS,DETAILS,4208 S ARCHER AVE,CHICAGO,IL,60632.0,15.0,26.0,15-26,9.0,1010,Limited Business License,1675683.0,RENEW,NaT,2007-06-21,2007-08-15,N,2007-08-16,2009-06-15,2007-08-15,2007-08-16,2008-03-26,39.0,41.816969,-87.699785,"{'latitude': '41.81696910012824', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,COVARRUBIAS,OTHER,0,0,0,0,1,3,0,1,0,0,1010,0,1,0,0,0,0,0,0,Limited Business License,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57234,1743194-20070816,1835677,266103,3,"GOODHEALTH MEDICAL PRODUCTS, INC.","GOODHEALTH MEDICAL PRODUCTS, INC.",2621 W 79TH ST,CHICAGO,IL,60652.0,18.0,14.0,18-14,8.0,1010,Limited Business License,1743194.0,RENEW,NaT,2007-06-21,2007-09-12,N,2007-08-16,2009-11-15,2007-09-12,2007-09-18,2008-03-17,NaN,41.749842,-87.688733,"{'latitude': '41.74984206916219', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,INC,INC,0,1,0,0,0,3,0,1,0,0,1010,0,1,0,0,0,0,0,0,Limited Business License,0,0,0,1,0,0,0,0,0
57235,2032383-20160716,2465962,63376,180,INTERPARK LLC,INTERPARK,505 N STATE ST 2-4,CHICAGO,IL,60654.0,42.0,22.0,42-22,18.0,1002,Accessory Garage,2032383.0,RENEW,NaT,2016-05-15,2016-06-23,N,2016-07-16,2018-07-15,2016-06-23,2016-08-11,2018-01-09,NaN,41.891055,-87.627898,"{'latitude': '41.89105524147196', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,LLC,LLC,0,0,1,0,0,OTHER SITE,0,0,0,1,OTHER LICENSE CODE,0,0,0,0,0,0,0,1,OTHER LICENSE DESC,0,0,0,0,0,1,0,0,0
57236,40376-20020216,1211199,55051,1,YUN HEE HWANG,TOP CLEANERS,1201 W ROSCOE ST 1ST,CHICAGO,IL,60657.0,44.0,9.0,44-9,19.0,1010,Limited Business License,40376.0,RENEW,NaT,2001-12-20,2002-01-18,N,2002-02-16,2003-02-15,2002-01-18,2002-01-22,NaT,NaN,41.943382,-87.659191,"{'latitude': '41.94338183750669', 'longitude':...",0,1,1,1,1,0,0,0,0,0,0,1,HWANG,OTHER,0,0,0,0,1,1,0,0,0,0,1010,0,1,0,0,0,0,0,0,Limited Business License,0,0,0,1,0,0,0,0,0
57237,2064176-20121116,2188497,357381,1,D. C. A. TOWING INCORPORATED,D. C. A. TOWING INCORPORATED,7052 W 64TH ST 1ST,CHICAGO,IL,60638.0,23.0,18.0,23-18,8.0,1012,Home Occupation,2064176.0,RENEW,NaT,2012-09-14,2012-12-25,N,2012-11-16,2014-11-15,2012-12-25,2012-12-26,2012-12-29,NaN,41.775710,-87.798009,"{'latitude': '41.775709631013335', 'longitude'...",0,1,1,1,1,1,0,0,0,0,0,1,INC,INC,0,1,0,0,0,1,0,0,0,0,1012,0,0,0,1,0,0,0,0,Home Occupation,0,1,0,0,0,0,0,0,0
57238,1954052-20090202,1954052,340610,1,maria t bedoy,mari's cleaning services,4544 S CHRISTIANA AVE 1,CHICAGO,IL,60632.0,14.0,10.0,14-10,8.0,1012,Home Occupation,1954052.0,ISSUE,NaT,2009-01-31,2009-01-31,N,2009-02-02,2009-06-15,2009-01-31,2009-02-02,NaT,39.0,41.810523,-87.707872,"{'latitude': '41.81052250782054', 'longitude':...",0,1,1,1,1,0,0,0,0,0,1,0,bedoy,OTHER,0,0,0,0,1,1,0,0,0,0,1012,0,0,0,1,0,0,0,0,Home Occupation,0,1,0,0,0,0,0,0,0

In [111]:
X_TESTING=test[['APPLICATION CREATE DATE ENCODED',
        'APPLICATION REQUEST COMPLETE ENCODED',
                        'PAYMENT DATE ENCODED',
             'LICENSE TERM START DATE ENCODED',
       'LICENSE APPROVED FOR ISSUANCE ENCODED',
          'LICENSE STATUS CHANGE DATE ENCODED',
                                      'C_CAPA',
                                      'C_EXPA',
                                       'C_LOC',
                                       'ISSUE',
                                       'RENEW',
                                 
                                 'CORPORATION',
                                         'INC',
                                         'LLC',
                                         'LTD',
                                       'OTHER',
                                             2,
                                             3,
                                             4,
                                  'OTHER SITE',
                                          1008,
                                          1010,
                                          1011,
                                          1012,
                                          1020,
                                          1525,
                                          1676,
                          'OTHER LICENSE CODE',
                         'Hazardous Materials',
                             'Home Occupation',
                                 'Home Repair',
                    'Limited Business License',
                           'Massage Therapist',
                          'OTHER LICENSE DESC',
           'Residential Real Estate Developer',
                   'Retail Food Establishment',
                          'Scavenger, Private']]

X_TESTING

In [114]:
preds=rfc.predict(X_TESTING.values)

In [ ]:
replacement_dict={'AAI':1,'AAC':2,'REV':3,'REA':4,'INQ':5}

df['LICENSE STATUS'].replace(replacement_dict,inplace=True)

In [118]:
test['LICENSE STATUS']=preds

In [116]:
test

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,APPLICATION CREATE DATE ENCODED,APPLICATION REQUEST COMPLETE ENCODED,PAYMENT DATE ENCODED,LICENSE TERM START DATE ENCODED,LICENSE APPROVED FOR ISSUANCE ENCODED,LICENSE STATUS CHANGE DATE ENCODED,C_CAPA,C_EXPA,C_LOC,C_SBA,ISSUE,RENEW,LEGAL TYPE,LEGAL TYPE CLASSIFIED,CORPORATION,INC,LLC,LTD,OTHER,SITE NUMBER ENCODED,2,3,4,OTHER SITE,LICENSE CODE ENCODED,1008,1010,1011,1012,1020,1525,1676,OTHER LICENSE CODE,LICENSE DESCRIPTION ENCODED,Hazardous Materials,Home Occupation,Home Repair,Limited Business License,Massage Therapist,OTHER LICENSE DESC,Residential Real Estate Developer,Retail Food Establishment,"Scavenger, Private",LICENSE STATUS ENCODED
0,1516615-20120216,2132209,280120,1,RS HOMES I LLC,RS HOMES I LLC,350 W HUBBARD ST 3 300,CHICAGO,IL,60610.0,42.0,67.0,42-67,18.0,1020,Residential Real Estate Developer,1516615.0,RENEW,NaT,2011-12-15,2012-01-19,N,2012-02-16,2014-02-15,2012-01-19,2012-01-20,2012-12-29,NaN,41.890047,-87.637467,"{'latitude': '41.89004724888915', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,LLC,LLC,0,0,1,0,0,1,0,0,0,0,1020,0,0,0,0,1,0,0,0,Residential Real Estate Developer,0,0,0,0,0,0,1,0,0,2
1,69813-20110616,2090759,65043,1,CSX INTERMODAL INC,CSX INTERMODAL,2101 W 59TH ST 1ST,CHICAGO,IL,60636.0,16.0,5.0,16-5,7.0,1010,Limited Business License,69813.0,RENEW,NaT,2011-04-15,2012-11-02,N,2011-06-16,2013-06-15,2012-11-02,2012-11-05,2012-12-29,NaN,41.786485,-87.676665,"{'latitude': '41.786485235679486', 'longitude'...",0,1,1,1,1,1,0,0,0,0,0,1,INC,INC,0,1,0,0,0,1,0,0,0,0,1010,0,1,0,0,0,0,0,0,Limited Business License,0,0,0,1,0,0,0,0,0,2
2,1519227-20041116,1541990,281270,1,LOCOMIBILE LOFTS LLC,LOCOMOBILE LOFTS LLC,1133 S WABASH AVE 1ST,CHICAGO,IL,60605.0,4.0,8.0,4-8,1.0,1020,Residential Real Estate Developer,1519227.0,RENEW,NaT,2004-09-27,2004-12-06,N,2004-11-16,2005-11-15,2004-12-06,2004-12-07,NaT,NaN,41.868269,-87.625695,"{'latitude': '41.86826924843568', 'longitude':...",0,1,1,1,1,0,0,0,0,0,0,1,LLC,LLC,0,0,1,0,0,1,0,0,0,0,1020,0,0,0,0,1,0,0,0,Residential Real Estate Developer,0,0,0,0,0,0,1,0,0,1
3,1922025-20100816,2041053,335243,1,ANNA F. JAMISON,ANNA F. JAMISON,13156 S FORRESTVILLE AVE,CHICAGO,IL,60827.0,9.0,33.0,9-33,5.0,1607,"Peddler, non-food, special",1922025.0,RENEW,NaT,2010-06-15,2010-11-04,N,2010-08-16,2012-08-15,NaT,2010-11-04,2012-12-31,NaN,41.655762,-87.608686,"{'latitude': '41.65576175146191', 'longitude':...",0,1,1,1,0,1,0,0,0,0,0,1,JAMISON,OTHER,0,0,0,0,1,1,0,0,0,0,OTHER LICENSE CODE,0,0,0,0,0,0,0,1,OTHER LICENSE DESC,0,0,0,0,0,1,0,0,0,2
4,1675683-20070816,1837158,283018,3,MARINCA A. COVARRUBIAS,DETAILS,4208 S ARCHER AVE,CHICAGO,IL,60632.0,15.0,26.0,15-26,9.0,1010,Limited Business License,1675683.0,RENEW,NaT,2007-06-21,2007-08-15,N,2007-08-16,2009-06-15,2007-08-15,2007-08-16,2008-03-26,39.0,41.816969,-87.699785,"{'latitude': '41.81696910012824', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,COVARRUBIAS,OTHER,0,0,0,0,1,3,0,1,0,0,1010,0,1,0,0,0,0,0,0,Limited Business License,0,0,0,1,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57234,1743194-20070816,1835677,266103,3,"GOODHEALTH MEDICAL PRODUCTS, INC.","GOODHEALTH MEDICAL PRODUCTS, INC.",2621 W 79TH ST,CHICAGO,IL,60652.0,18.0,14.0,18-14,8.0,1010,Limited Business License,1743194.0,RENEW,NaT,2007-06-21,2007-09-12,N,2007-08-16,2009-11-15,2007-09-12,2007-09-18,2008-03-17,NaN,41.749842,-87.688733,"{'latitude': '41.74984206916219', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,INC,INC,0,1,0,0,0,3,0,1,0,0,1010,0,1,0,0,0,0,0,0,Limited Business License,0,0,0,1,0,0,0,0,0,2
57235,2032383-20160716,2465962,63376,180,INTERPARK LLC,INTERPARK,505 N STATE ST 2-4,CHICAGO,IL,60654.0,42.0,22.0,42-22,18.0,1002,Accessory Garage,2032383.0,RENEW,NaT,2016-05-15,2016-06-23,N,2016-07-16,2018-07-15,2016-06-23,2016-08-11,2018-01-09,NaN,41.891055,-87.627898,"{'latitude': '41.89105524147196', 'longitude':...",0,1,1,1,1,1,0,0,0,0,0,1,LLC,LLC,0,0,1,0,0,OTHER SITE,0,0,0,1,OTHER LICENSE CODE,0,0,0,0,0,0,0,1,OTHER LICENSE DESC,0,0,0,0,0,1,0,0,0,2
57236,40376-20020216,1211199,55051,1,YUN HEE HWANG,TOP CLEANERS,1201 W ROSCOE ST 1ST,CHICAGO,IL,60657.0,44.0,9.0,44-9,19.0,1010,Limited Business License,40376.0,RENEW,NaT,2001-12-20,2002-01-18,N,2002-02-16,2003-02-15,2002-01-18,2002-01-22,NaT,NaN,41.943382,-87.659191,"{'latitude': '41.94338183750669', 'longitude':...",0,1,1,1,1,0,0,0,0,0,0,1,HWANG,OTHER,0,0,0,0,1,1,0,0,0,0,1010,0,1,0,0,0,0,0,0,Limited Business License,0,0,0,1,0,0,0,0,0,1
57237,2064176-20121116,2188497,357381,1,D. C. A. TOWING INCORPORATED,D. C. A. TOWING INCORPORATED,7052 W 64TH ST 1ST,CHICAGO,IL,60638.0,23.0,18.0,23-18,8.0,1012,Home Occupation,2064176.0,RENEW,NaT,2012-09-14,2012-12-25,N,2012-11-16,2014-11-15,2012-12-25,2012-12-26,2012-12-29,NaN,41.775710,-87.798009,"{'latitude': '41.775709631013335', 'longitude'...",0,1,1,1,1,1,0,0,0,0,0,1,INC,INC,0,1,0,0,0,1,0,0,0,0,1012,0,0,0,1,0,0,0,0,Home Occupation,0,1,0,0,0,0,0,0,0,2
57238,1954052-20090202,1954052,340610,1,maria t bedoy,mari's cleaning services,4544 S CHRISTIANA AVE 1,CHICAGO,IL,60632.0,14.0,10.0,14-10,8.0,1012,Home Occupation,1954052.0,ISSUE,NaT,2009-01-31,2009-01-31,N,2009-02-02,2009-06-15,2009-01-31,2009-02-02,NaT,39.0,41.810523,-87.707872,"{'latitude': '41.81052250782054', 'longitude':...",0,1,1,1,1,0,0,0,0,0,1,0,bedoy,OTHER,0,0,0,0,1,1,0,0,0,0,1012,0,0,0,1,0,0,0,0,Home Occupation,0,1,0,0,0,0,0,0,0,1

In [119]:
replacement_dict_rev={1:'AAI',2:'AAC',3:'REV',4:'REA',5:'INQ'}
test['LICENSE STATUS'].replace(replacement_dict_rev,inplace=True)

In [123]:
submission2=test[['ID','LICENSE STATUS']]

In [124]:
submission2.set_index('ID',inplace=True)

In [128]:
submission2.to_csv('submission2')

### Thank you for this opportunity, it was a reallly fun experience working on this model!